{
    "url": "https://www.producthunt.com/categories/automation",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/7a01a00b-d41d-4367-b44e-e1d0a672819b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Stripe — Financial infrastructure for the internet",
        "description": "Accept payments, send payouts, automate financial processes, and ultimately grow revenue.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""

      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/d4ad8bb6-7bd5-4e3c-93af-b69c553312ed.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Expo — An open-source platform for building native apps",
        "description": "Build, deploy, and quickly iterate on native Android, iOS, and web apps from the same JavaScript codebase.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/f01f527e-e5f9-4822-8f11-bfac2ed71eb8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Remotion — Create videos programmatically",
        "description": "Make real MP4 videos written in React using CSS, SVG, and WebGL to make interesting motion graphics. Use programming to dynamically make different variants of videos and automate it using server-side rendering.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/9acdbce2-d993-489b-b6e3-afb817d04d0b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Zapier — Connect your apps and automate workflows",
        "description": "Easy automation for busy people. Zapier empowers you to automate your work across 5,000+ apps—so you can move forward, faster.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/96034044-b256-4eff-9a6e-551b78203862.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Tailwind UI — Beautiful UI components, by the creators of Tailwind CSS",
        "description": "Beautifully designed, expertly crafted components and templates, built by the makers of Tailwind CSS.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/f2fe3365-9ba8-498a-b1fe-e74bbd5b425e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Trigger.dev — The open source background jobs framework",
        "description": "Create long-running jobs directly in your codebase with features like API integrations, webhooks, scheduling and delays.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/a46e2608-8f72-4a89-82e0-abbe70f10f83.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS Lambda — An event-driven, serverless computing platform",
        "description": "A compute service that runs your code in response to events and automatically manages the compute resources, making it the fastest way to turn an idea into a modern, production, serverless applications.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/7773976d-e914-4046-91b1-154f91680d94.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Shipixen — Create a blog & landing page in minutes",
        "description": "Create a production-ready landing page & blog with your branding, theme & pages. You get the code & an SEO-optimized website so you can focus on building, not setting up.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "icon": "https://ph-files.imgix.net/72dfe2ac-646f-44a8-9a6d-5d8097ccc835.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Albato — A no-code platform for all automations",
        "description": "Integrate your applications into automated workflows using a no code builder.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/a6f3b218-e87c-460c-93f6-b5ea9d9de223.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "monday.com — One platform for managing any project, task, and workflow",
        "description": "Used by 180K+ global customers, monday.com is a customizable and easy-to-use work management platform that maximizes efficiency, boosts collaboration, and increases productivity. Easily plan, centralize, streamline, and automate your teams' work and projects by utilizing powerful features such as no-code automations, real-time notifications, customizable dashboards, 200+ pre-made templates, multiple views, 72+ integrations, and more. From idea to execution, manage it all on one robust platform.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/33bbc115-24f5-4c27-adb2-ef011c50b576.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Make — Design, build and automate your work",
        "description": "A visual platform for anyone to design, build, and automate anything—from tasks and workflows to apps and systems—without coding.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/32c58a09-b2a0-4669-ab9e-d31ce9e44ff1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Docker — Accelerate how you build, share, and run applications",
        "description": "Build, share, run, and verify applications anywhere without tedious environment configuration or management.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/78eabb8b-7ef3-4bbb-98f0-e6cadb155b09.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Relay.app — The new standard for automation",
        "description": "Relay.app is the easiest-to-use Zapier alternative that lets you automate workflows with powerful AI and Human-in-the-Loop features.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/24a944d4-ad23-4fcc-93a6-018fad330b9f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Dokin — Sync live data from apps in Sheets, Slides, and Docs",
        "description": "Connect marketing channels, CRMs, and databases to Google Sheets and Looker with no-code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "",
        "icon": "https://ph-files.imgix.net/e7891aa5-d7bc-4241-82d5-60bffa53d148.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Svix — Webhooks as a service",
        "description": "Build a secure, reliable, and scalable webhook sending platform",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name": "",
        "icon": "https://ph-files.imgix.net/ad462085-d7ad-432a-828d-a9e2419fbbc5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Intros.ai — Boost community engagement by automating interactions.",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name": "",
        "icon": "https://ph-files.imgix.net/bf1ebcaf-674d-45fe-aec6-debe967022d1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Approximated — Offer custom automated domains as a feature to your users.",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name": "",
        "icon": "https://ph-files.imgix.net/e277d09d-84de-4555-ba92-8b8e5a39d763.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Raycast — Application launcher and productivity software",
        "description": "A blazingly fast, totally extendable launcher. It lets you complete tasks, calculate, share common links, and much more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name": "",
        "icon": "https://ph-files.imgix.net/927733c0-76ff-402b-af77-e09cbd88f1cd.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cursor Copilot++ — Autocomplete redesigned to predict your next edit",
        "description": "A more powerful version of Copilot that can suggest mid-line completions and entire diffs. Trained to autocomplete on sequences of edits, it's quick to understand the change you're making.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name": "",
        "icon": "https://ph-files.imgix.net/5b05dea5-50a7-49f1-ae6d-80c3970f8ab5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Re:catch — Automate your inbound pipeline, and close a deal by tomorrow",
        "description": "Re:catch is a cloud-based sales funnel automation software that empowers revenue teams to achieve revenue acceleration by optimizing Speed-to-Lead and Time-to-Revenue.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "21",
        "name": "",
        "icon": "https://ph-files.imgix.net/bd81d0d1-9c8c-4123-bf66-bd79251da340.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Clay — Build tools & workflows to supercharge your sales team",
        "description": "Quickly connect your apps and code into automated workflows, build useful tools, enrich data sets and more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "22",
        "name": "",
        "icon": "https://ph-files.imgix.net/fd433044-5823-48aa-8de1-89eb2c49501d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Veryfi — OCR API for data extraction from documents",
        "description": "Secure data extraction OCR API, data capture mobile SDK, and toolkits to liberate trapped data in your unstructured documents like invoices, bills, purchase orders, checks (cheques) and receipts in real-time.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "23",
        "name": "",
        "icon": "https://ph-files.imgix.net/66a85c2a-4f35-4a18-be1d-2859cb28e5fb.x-icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Trello 2 — Manage your team’s projects from anywhere",
        "description": "Trello is the ultimate project management tool. Start up a board in seconds, automate tedious tasks, and collaborate anywhere, even on mobile.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "24",
        "name": "",
        "icon": "https://ph-files.imgix.net/54a7eafd-ba59-41a8-a0bd-860ec90ccf80.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Craftar — Craft Automations Visually",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "25",
        "name": "",
        "icon": "https://ph-files.imgix.net/8da2264e-1cf0-4057-a292-3aaf41b59423.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Paragon — Integrate with your users' other SaaS apps - 7x faster.",
        "description": "Engineering teams use Paragon's Embedded iPaaS to integrate their applications users' 3rd party tools like Salesforce, Slack, Google Drive with 70% less engineering. Build bi-directional record syncs, ingest 3rd party data to train your LLMs, or automate processes in your users' integrated accounts - all without worrying about the plumbing (auth, rate limits, concurrency etc.). Better yet? You can author these integrations in our visual workflow builder or in code!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "26",
        "name": "",
        "icon": "https://ph-files.imgix.net/12070d97-a559-457a-853f-27cafd9fa8c1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Bottomright AI — AI chatbot that trains itself on your website",
        "description": "Meet Bottomright — the AI powered chatbot that trains itself by crawling your website. Add it to yours in minutes and put customer support on autopilot.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "27",
        "name": "",
        "icon": "https://ph-files.imgix.net/c5021d06-66b4-4fcc-b8ee-a3f4c862fb67.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "n8n — Workflow automation for technical people",
        "description": "n8n is a source-available workflow automation tool designed for technical users. Our low-code platform offers a seamless blend of code and an intuitive interface, serving as the perfect bridge between engineers and other people at your organization.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "28",
        "name": "",
        "icon": "https://ph-files.imgix.net/1f885b01-0d52-48b7-a8af-74b4dac2b6b4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "LocalizeBot — Translate iOS app In 1 click",
        "description": "Simplifies app localization and helps you reach more users. Use a machine translation service to translate your App and App Store metadata. - Supported xliff and xcloc files. - Translate App Store metadata.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "29",
        "name": "",
        "icon": "https://ph-files.imgix.net/6fedb2b3-4abe-47f0-999b-cac7a91b5a39.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Statsig — #1 feature management and product experimentation platform",
        "description": "Statsig is the leading product experimentation platform that helps businesses use data to ship fast and build better products. Companies like OpenAI, Notion, Brex, and Eventbrite use Statsig to manage feature rollouts, automate experiments, and make decisions based on performance metrics. Founded in 2021 by former Facebook engineers, Statsig supports thousands of experiments impacting over a billion end users globally.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "30",
        "name": "",
        "icon": "https://ph-files.imgix.net/32efc42b-f2e6-449e-a674-0308fa73cae8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Chatwith — Instantly answer questions with a custom AI chatbot",
        "description": "Create a support agent trained on your content and back-end data. Let it handle all customer questions, from realtime inventory information to document generation. Boost your customer service and cut your support workload.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "31",
        "name": "",
        "icon": "https://ph-files.imgix.net/e4d1fd37-12e5-482b-8a71-f4ca9b1d006d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Roadway — Take the guesswork out of growth marketing",
        "description": "Roadway is the first analytics and automation platform purpose-built for growth marketing teams to unlock faster and more efficient revenue growth. Quickly create dashboards, reports, and automate growth analysis to optimize and scale growth channels faster.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "32",
        "name": "",
        "icon": "https://ph-files.imgix.net/853e16e5-2f1d-48b9-ac05-73ee867f1044.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Play — Making AI speak better than humans.",
        "description": "Leaders in Conversational Voice AI. We're building generative AI voices for the conversational future. Join https://discord.gg/yBbq7UfUsF",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "33",
        "name": "",
        "icon": "https://ph-files.imgix.net/d81028ec-db98-4c7c-a69a-d1a43f28d9d8.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "WorkGPT: Combination of ChatGPT & Zapier — AI Agent Chatbot-based Virtual Assistant",
        "description": "WorkGPT, a chatbot-based platform empowering users to create your very own virtual assistants that work tirelessly. You can seamlessly connect with various tools and applications, enhancing productivity and streamlining tasks effortlessly.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "34",
        "name": "",
        "icon": "https://ph-files.imgix.net/bd43291e-557a-4a92-a46c-669d638985d2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "NixOS — Reproducible builds and deployments.",
        "description": "Nix is a tool that takes a unique approach to package management and system configuration. Learn how to make reproducible, declarative and reliable systems.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "35",
        "name": "",
        "icon": "https://ph-files.imgix.net/5aef40ff-3d74-405b-a375-993e1fdb26f7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "GitHub Actions — Automate your workflow from idea to production",
        "description": "GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. Make code reviews, branch management, and issue triaging work the way you want.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "36",
        "name": "",
        "icon": "https://ph-files.imgix.net/ccfccd7d-6a10-4d3e-9cd9-eaff6e339f8f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ansible — Ansible is the simplest way to automate",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "37",
        "name": "",
        "icon": "https://ph-files.imgix.net/29c5bafb-178f-41d4-bdcf-b3a9dcd978b0.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Chargebee — The smartest way to set up your subscription billing.",
        "description": "Chargebee's subscription billing software powers end-to-end recurring billing for subscription businesses with smart automation.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "38",
        "name": "",
        "icon": "https://ph-files.imgix.net/c2963758-f210-4e02-a3a2-b57c542f9841.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Text Blaze — Eliminate repetitive typing and mistakes.",
        "description": "Easy-to-use templates with endless customizability and powerful automation. All with full control at your fingertips.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "39",
        "name": "",
        "icon": "https://ph-files.imgix.net/9c69a09a-46c0-4a52-8172-3e4e7fa54643.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Mintlify — Developer communication platform",
        "description": "Mintlify lets fast growing teams enable continuous documentation into a standard practice. Mintlify sets up rules and automations to ensure that software teams can easily create, track and manage documentation.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "40",
        "name": "",
        "icon": "https://ph-files.imgix.net/ea4a0d07-c204-46b0-aa9e-5b180e0af8e9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sheety — Turn your Google Sheet into an API instantly, for free",
        "description": "Turn any Google sheet into an API instantly, for free. Power websites, apps, or whatever you like, all from a spreadsheet. Changes to your spreadsheet update your API in realtime.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "41",
        "name": "",
        "icon": "https://ph-files.imgix.net/42fe4fbb-8537-45c2-bfbd-8e2961bf4525.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Porter — PaaS you cannot outgrow",
        "description": "Porter brings the magical experience of deploying an application with just a few clicks into your own AWS or GCP account. Porter will manage the underlying infrastructure for you - simply point at your repo and Porter will handle the rest, from building your application to autoscaling it.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "42",
        "name": "",
        "icon": "https://ph-files.imgix.net/3d81a8a3-7984-4a99-9050-f54e574bcb0f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Octomind — Find bugs before your users do with AI",
        "description": "AI-powered testing tool for web apps that finds bugs before your users do. We only need your website’s URL. Our AI agent knows what to test, writes the tests and keeps them relevant. Run the tests from our app or plug them into your CI/CD pipeline.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "43",
        "name": "",
        "icon": "https://ph-files.imgix.net/f612d983-443f-461c-912b-a7593238f057.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Hatchbox — We'll take care of everything for you.",
        "description": "Hatch is way for you to deploy Rails apps to your own servers at places like Digital Ocean as easily as Heroku. We'll take care of installing Ruby, Nginx, PostgreSQL, Redis and more and even manage environment variables and all the other little details for you.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "44",
        "name": "",
        "icon": "https://ph-files.imgix.net/6a77e0da-ac55-4f02-91f9-cd4fc2c6ed1d.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Pipedream — Connect APIs, remarkably fast.",
        "description": "Pipedream is an integration platform for developers, with over 800k customers across 10k companies. Our customers use Pipedream to build automation between over 2000 integrated applications today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "45",
        "name": "",
        "icon": "https://ph-files.imgix.net/08a5ddbf-62fa-4c91-9210-8d1fa07409f4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sidekiq — The best background processing for Ruby",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "46",
        "name": "",
        "icon": "https://ph-files.imgix.net/450f63b2-68bf-4035-a56f-2fb799e3040c.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Flightcontrol — Developer-first AWS Infrastructure",
        "description": "Designed for teams that want the benefits & reliability of AWS without hiring devops",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "47",
        "name": "",
        "icon": null,
        "title": "SwiftShip — Build and Ship your iOS app in a few days or hours",
        "description": "A Swift UI Boilerplate that takes care of features commonly needed in mobile apps, and lets you save time and focus on your value proposition and main features. Save hours of development and ship your iOS app in a few days or hours.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "48",
        "name": "",
        "icon": "https://ph-files.imgix.net/7a4ae8ac-fafc-43d9-8156-f2eb8327b6b2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Backpack for Laravel — Feature-packed admin panel for Laravel apps.",
        "description": "Build custom admin panels 10x faster. Backpack will help you generate CRUDs for your Eloquent models, and easily create custom CRUDs for complex use cases.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "49",
        "name": "",
        "icon": "https://ph-files.imgix.net/db4a43f7-eb23-42c2-becf-ed5b21868581.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "JustDeploy — Deploy to your server in minutes, not weeks for as low as $4",
        "description": "Launch from your machine to your VPS for as little as $4 with our automation template. Experience complete freedom and cost control from development to production. Scale as you grow!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "50",
        "name": "",
        "icon": "https://ph-files.imgix.net/b5076082-e97c-40ca-9820-d82b6c55602a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sieve — Process and search 24 hours of video in less than 10 mins",
        "description": "Sieve is an API that helps you store, process, and automatically search video data–instantly and efficiently. Find the 1% of data that’s interesting within petabytes of raw video, tag important metadata, and build high-quality datasets with Sieve.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "51",
        "name": "",
        "icon": "https://ph-files.imgix.net/fe2d6b1c-4c23-447d-915c-6e99d1a002db.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Phrase — Unlock language. Unlock opportunity.",
        "description": "Open the door to global business and drive growth with the world’s most powerful, connective, and customizable localization platform. The Phrase Localization Suite is built to automate, manage, and translate all your content into the languages your audiences speak, and the experiences they live.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "52",
        "name": "",
        "icon": "https://ph-files.imgix.net/3443abae-a785-4364-b97a-c1ebb8714310.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Picasso — Professional App Store screenshots in minutes, not hours",
        "description": "Increase your product page conversion by up to 30%. Picasso's powerful App Store screenshot editor can help you optimize your screenshot workflow. Localize with ease using String Catalogs. Then, once you're done, upload them directly to App Store Connect.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "53",
        "name": "",
        "icon": "https://ph-files.imgix.net/045e1776-1aef-441d-901a-d5870829fee8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "OpenAI Tools — Super App For Fine-tuning Datasets, Jobs, Metrics & Models",
        "description": "Toolkit to get the most out of your OpenAI account: Track API usage; Manage ChatGPT fine-tuning datasets; Create, monitor and cancel fine-tuning jobs; Review and visualize training logs; Test and compare fine-tuned and other models directly, and more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "54",
        "name": "",
        "icon": "https://ph-files.imgix.net/cf942563-41e3-4591-a6eb-3c7f738a135b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Gadget — The fastest way to build and run web apps",
        "description": "Gadget is a full-stack, serverless JavaScript platform for web app developers who want to build faster and maintain less. Skip the boilerplate features, repetitive code, and busywork, and get your ideas out the door in hours.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "55",
        "name": "",
        "icon": "https://ph-files.imgix.net/294a07d2-7039-445e-ab71-89fb51bdf139.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Billy (birthday bot for Slack) — Never forget a teammate's birthday again",
        "description": "🎉 Automates birthday and work anniversary celebrations in Slack. 🎉 Join thousands of companies who brought fun into their workplace. Install now for free (in less than 30s ⚡️)",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "56",
        "name": "",
        "icon": "https://ph-files.imgix.net/64fbf1dc-4c49-43c6-9d1d-58f45c8573ee.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Mandrill — Transactional emails from MailChimp",
        "description": "A delivery API, or application programming interface, that can deliver transactional emails to customers without you overseeing the process.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "57",
        "name": "",
        "icon": "https://ph-files.imgix.net/76c7ac98-1faf-4131-98c0-57ef404d50f8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Zuar — Business analytics, data staging/pipeline & automation",
        "description": "Zuar provides cutting-edge data tools: Mitto ETL automation, data transformation/modeling, Tableau enhancements, and seasoned engineers to help with deployments.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "58",
        "name": "",
        "icon": "https://ph-files.imgix.net/3b26acd2-c3f4-4352-b1d5-24ffc2f465ef.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Creatomate — Create & automate videos by API and no-code",
        "description": "Creatomate is a video generation API for developers and Zapier users. Create reusable templates to automate and scale your video production with code or no-code tools. Auto-generate videos for social media, personalization, e-commerce, advertising, and more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "59",
        "name": "",
        "icon": "https://ph-files.imgix.net/0f4f1f87-ba3b-458c-81df-35582213f903.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Helm for App Store Connect — Easy Application Management",
        "description": "Meet Helm, an app designed to make it easier and more enjoyable for users of App Store Connect to ship apps and updates. Focused on providing a fast & intuitive user experience.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "60",
        "name": "",
        "icon": "https://ph-files.imgix.net/78d34ec5-5904-47c5-af57-3eb71655c901.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Create Go App — Create a new production-ready project by one CLI command",
        "description": "Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command. Focus on writing code and thinking of business-logic! The CLI will take care of the rest.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "61",
        "name": "",
        "icon": "https://ph-files.imgix.net/948ff980-54cd-4e1c-b9fd-f79a8d7e8638.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Vanta — Automate compliance and streamline security reviews",
        "description": "Whether you’re starting or scaling your security program, Vanta helps you automate compliance across frameworks like SOC 2, ISO 27001, ISO 42001, HIPAA, HITRUST CSF, GDPR, and more. Streamline security reviews by automating questionnaires and demonstrating your security posture with a customer-facing Trust Center, all powered by Vanta AI. Over 7,000 global companies like Atlassian, Flo Health, and Quora use Vanta to manage risk and prove security in real time.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "62",
        "name": "",
        "icon": "https://ph-files.imgix.net/09e133eb-7f0f-4175-a272-d5d5c7a0a99b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Instafill — Fill PDF forms with AI",
        "description": "Facing challenges with filling out PDF forms? InstaFill uses Al to understand and complete fields for you, especially when you're unsure about how to fill them. Let us handle the paperwork while you focus on what matters.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "63",
        "name": "",
        "icon": "https://ph-files.imgix.net/8e509d6c-5aea-4c10-a945-643642e25eb5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Fortune — An AI-powered accountant",
        "description": "Connect all your banks in one place, leverage AI to automate accounting, track cash flow, and forecast.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "64",
        "name": "",
        "icon": "https://ph-files.imgix.net/62a86d12-e385-4ff1-9bdd-017d2de22474.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ellipsis — AI code reviews & bug fixes",
        "description": "Ellipsis is a GitHub app that automatically reviews code and fixes bugs on pull requests. It catches logical bugs, enforces your team's style guide, and can even generate working, tested code to address comments like \"@ellipsis-dev fix this unit test\"",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "65",
        "name": "",
        "icon": "https://ph-files.imgix.net/ca00908a-9631-477e-be3b-a5cf9f4afdbc.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Robolly — Dynamic images, videos & PDFs via Google Sheets or API",
        "description": "Robolly is an all-in-one service for automated image, video & PDF generation. The potential is limitless; you can use it to generate branded social media content, open graph images, PDF certificates, personalized videos, slideshows, and so much more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "66",
        "name": "",
        "icon": "https://ph-files.imgix.net/a3a5a8d6-2705-4bdf-83a7-e72886f71c3c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Glasskube — 🧊 The next generation Package Manager for Kubernetes 📦",
        "description": "Building on the pitfalls of other popular package managers in the ecosystem, we aim to deliver streamlined package updates, easy GitOps integration, package dependency management, and simplified configuration options.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }