{
    "url": "https://www.producthunt.com/categories/command-line-tools",
    "productCards": [
      {
        "rank": "1",
        "name":"",
        "icon": "https://ph-files.imgix.net/53213ebd-6c42-4ec4-839a-8d40a4206354.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Vite — Next Generation Frontend Tooling",
        "description": "Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects. A dev server that provides rich feature enhancements. A build command that bundles your code, pre-configured to output highly optimized static assets.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name":"",
        "icon": "https://ph-files.imgix.net/73e8b4ab-4112-4c4e-b475-e1c5923d01e4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Rust — A high-level, safe and concurrent alternative to C++",
        "description": "A blazingly fast and memory-efficient programming language with no runtime or garbage collector. It can power performance-critical services, run on embedded devices, and easily integrate with other languages.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name":"",
        "icon": "https://ph-files.imgix.net/6c17a03d-52c6-4c6a-b521-bf84de68591b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Convex — A better type of backend",
        "description": "Convex is a full-stack TypeScript development platform that keeps you focused on your product. Use our realtime database to build apps that are reactive by default. Integrate OpenAI into your workflows with builtin functions, scheduling, and vector search.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name":"",
        "icon": "https://ph-files.imgix.net/d5a12d33-9700-47e4-90b9-24b07edbd05d.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Electron — platform desktop apps with JavaScript, HTML, and CSS",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name":"",
        "icon": "https://ph-files.imgix.net/6bad3f69-e994-422a-b532-569cbb4ee076.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Astro — The web framework that scales with you.",
        "description": "Build fast content-driven websites, powerful SPA web applications, dynamic server APIs and everything in-between.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name":"",
        "icon": "https://ph-files.imgix.net/1c3afe83-3ee9-4725-b586-f38f9deb8e2b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Go Language — Go is an open source programming language",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name":"",
        "icon": "https://ph-files.imgix.net/34177e7f-0f0d-4a4f-a872-65cbd506bae7.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Python Awesome — A nice collection of often useful awesome Python libraries.",
        "description": "A nice collection of often useful awesome Python frameworks, libraries and software.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name":"",
        "icon": "https://ph-files.imgix.net/02a2dbcc-3c93-40eb-85d9-2b5b77411b8c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Warp — The terminal for the 21st century",
        "description": "Warp is a fast Rust-based terminal that’s easy to use and built for teams. 1) Commands and outputs are grouped like a data notebook 2) Input is a modern code-editor preconfigured with useful completions 3) Share outputs via links 4) Save and run team commands",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name":"",
        "icon": "https://ph-files.imgix.net/326ef23f-183c-40fa-a8d9-67718e1386eb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "T3 Stack, Next and React File Generator — Next.js with T3 Stack in VSCode: Effortless file generation.",
        "description": "🚀 Boost your Next.js development with this extension for VSCode. Streamline file generation and optimize your project's lifecycle. Easily craft pages, components, layouts, and more. Includes commands and snippets for Next.js, Prisma, tRPC, and key frameworks.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name":"",
        "icon": "https://ph-files.imgix.net/5b8f843b-51e2-4482-8f9f-a0535151462a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "snap2txt — Convert your project into prompt",
        "description": "snap2txt is a Python utility that captures the structure and contents of a project directory and saves them into a text file. This text file is a ready-to-use base for a prompt to develop new features with ChatGPT.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name":"",
        "icon": "https://ph-files.imgix.net/e464fdb2-04f0-45c1-ae0e-407f6887c5fb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Kotlin — Statically typed programming language targeting the Java /JS",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name":"",
        "icon": "https://ph-files.imgix.net/db4a43f7-eb23-42c2-becf-ed5b21868581.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "JustDeploy — Deploy to your server in minutes, not weeks for as low as $4",
        "description": "Launch from your machine to your VPS for as little as $4 with our automation template. Experience complete freedom and cost control from development to production. Scale as you grow!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name":"",
        "icon": "https://ph-files.imgix.net/f85cffd0-9545-4a3d-b506-80e4066bd8de.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Turbo — Make Ship Happen",
        "description": "Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name":"",
        "icon": "https://ph-files.imgix.net/092e5e79-46ae-4713-8e8b-94d112d0b5e8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "npm — A package manager for javascript",
        "description": "Relied upon by more than 11 million developers worldwide, npm is committed to making JavaScript development elegant, productive, and safe. The free npm Registry has become the center of JavaScript code sharing, and with more than one million packages, the largest software registry in the world. Our other tools and services take the Registry, and the work you do around it, to the next level.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name":"",
        "icon": "https://ph-files.imgix.net/500aee69-72a2-44e9-831d-f630fa591840.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AdonisJS — MVC Framework for NodeJs to write webapps with less code",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name":"",
        "icon": "https://ph-files.imgix.net/42ef2886-cad4-484f-9c20-01236dedb6c0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Nx — Smart, Fast and Extensible Build System",
        "description": "Nx is a next-generation-build system with first-class support for both standalone projects and monorepos.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name":"",
        "icon": "https://ph-files.imgix.net/78d34ec5-5904-47c5-af57-3eb71655c901.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Create Go App — Create a new production-ready project by one CLI command",
        "description": "Create a new production-ready project with backend (Golang), frontend (JavaScript, TypeScript) and deploy automation (Ansible, Docker) by running one CLI command. Focus on writing code and thinking of business-logic! The CLI will take care of the rest.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name":"",
        "icon": "https://ph-files.imgix.net/b7f66023-1b8e-496c-8d52-8a81950c49e7.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "RubyGems — Find, install, and publish RubyGems",
        "description": "The Ruby community’s gem hosting service. Instantly publish your gems and then install them. Use the API to find out more about available gems.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name":"",
        "icon": "https://ph-files.imgix.net/a3a5a8d6-2705-4bdf-83a7-e72886f71c3c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Glasskube — 🧊 The next generation Package Manager for Kubernetes 📦",
        "description": "Building on the pitfalls of other popular package managers in the ecosystem, we aim to deliver streamlined package updates, easy GitOps integration, package dependency management, and simplified configuration options.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name":"",
        "icon": "https://ph-files.imgix.net/9a496822-69dd-42fb-bbf3-d081c129c850.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Redux Dev Tools — DevTools for Redux with hot reloading, action replay",
        "description": "Developer Tools to power-up Redux development workflow or any other architecture which handles the state change. It can be used as a browser extension (for Chrome and Firefox), as a standalone app or as a React component integrated in the client app.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }