{
    "url": "https://www.producthunt.com/categories/code-editors",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/c07d85e1-8ac0-4793-8cc5-3b413644371d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Xcode — Develop, test, and distribute apps for all Apple platforms",
        "description": "Code and design your apps faster with enhanced code completion, interactive previews, and live animations. Use Git staging to craft your next commit without leaving your code. Explore and diagnose your test results with redesigned test reports with video recording. And start deploying seamlessly to TestFlight and the App Store from Xcode Cloud. Creating amazing apps has never been easier.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/a32a6a01-1bfe-49df-b196-b9cc342c5175.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "VS Code — Microsoft Visual Studio Code lets you build and debug apps",
        "description": "Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/8fd47ed2-7e09-42c0-8a09-9e66744ab17d.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Laravel Framework — The PHP Framework for Web Artisans",
        "description": "Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/a91a21ee-1d99-4713-87a9-7466c778feb9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "JetBrains — A suite of intelligent development tools",
        "description": "Powerful IDEs for most programming languages and technologies along with products for team collaboration.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/cdb23f26-b385-4854-a005-3862be50f79e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "GitHub Copilot Chat — AI chat features powered by Copilot",
        "description": "GitHub Copilot Chat is a companion extension to GitHub Copilot that provides conversational AI assistance throughout your software development journey in VS Code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/73e8b4ab-4112-4c4e-b475-e1c5923d01e4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Rust — A high-level, safe and concurrent alternative to C++",
        "description": "A blazingly fast and memory-efficient programming language with no runtime or garbage collector. It can power performance-critical services, run on embedded devices, and easily integrate with other languages.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/0643ccd3-579d-4a56-bdbb-17e68793ab86.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "vscode.dev — Bringing VS Code to the browser",
        "description": "Now when you go to https://vscode.dev, you'll be presented with a lightweight version of VS Code running fully in the browser. Open a folder on your local machine and start coding. No install required.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/1c3afe83-3ee9-4725-b586-f38f9deb8e2b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Go Language — Go is an open source programming language",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/34177e7f-0f0d-4a4f-a872-65cbd506bae7.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Python Awesome — A nice collection of often useful awesome Python libraries.",
        "description": "A nice collection of often useful awesome Python frameworks, libraries and software.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/5e384dcc-8e07-4d0a-93b6-720c0bb005b6.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Zed — Code at the speed of thought",
        "description": "Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/5d5f3851-a353-4bce-abb1-1bf326ef5c74.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "StackBlitz — StackBlitz is an instant fullstack web IDE for the JavaScript ecosystem.",
        "description": "StackBlitz is an instant fullstack web IDE for the JavaScript ecosystem. It's powered by WebContainers, the first WebAssembly-based operating system which boots Node.js environment in milliseconds, securely within your browser tab.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/927733c0-76ff-402b-af77-e09cbd88f1cd.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cursor Copilot++ — Autocomplete redesigned to predict your next edit",
        "description": "A more powerful version of Copilot that can suggest mid-line completions and entire diffs. Trained to autocomplete on sequences of edits, it's quick to understand the change you're making.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/edaab87b-37ea-430d-8979-45e1b9f79c52.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Visual Studio — Visual Studio: IDE and Code Editor for Software Developers and Teams",
        "description": "Visual Studio dev tools & services make app development easy for any developer, on any platform & language. Develop with our code editor or IDE anywhere for free.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/b3352e6c-466e-4968-b820-ec615cad94be.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Php 8 — scripting language that powers many websites in the world.",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/e3aed385-a539-4647-bf1e-df746e735131.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Quasar IntelliSense — Simplified Quasar css development in VS Code.",
        "description": "Quasar IntelliSense: Effortlessly enhance your Quasar development in Visual Studio Code with CSS class autocompletion. Save time, minimize errors, and simplify your workflow for a more efficient and effective coding experience.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/5e0842a9-d219-4c9e-be3e-9b051e2e6d40.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Drizzle ORM — A lightweight and performant TypeScript ORM",
        "description": "Drizzle is a lightweight, tree shakeable modern TypeScript ORM with 0 dependencies.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/4899f4ca-6979-45a3-9241-15e031f76d69.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Typescript React Native Starter — An open source Typescript React Native boilerplate",
        "description": "This is an opionated configuration for Typescript React Native with all the packages and tools that I use for my React Native projects. Feel free to contribute.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/02a2dbcc-3c93-40eb-85d9-2b5b77411b8c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Warp — The terminal for the 21st century",
        "description": "Warp is a fast Rust-based terminal that’s easy to use and built for teams. 1) Commands and outputs are grouped like a data notebook 2) Input is a modern code-editor preconfigured with useful completions 3) Share outputs via links 4) Save and run team commands",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/4351458f-922c-4c5c-acb3-2a0e2dfc9edf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Continue — Continue enables you to create your own AI code assistant",
        "description": "Continue enables you to create your own AI code assistant inside your IDE. Keep your developers in flow with open-source VS Code and JetBrains extensions that can be connected to any model, any context, and anything else you need",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/326ef23f-183c-40fa-a8d9-67718e1386eb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "T3 Stack, Next and React File Generator — Next.js with T3 Stack in VSCode: Effortless file generation.",
        "description": "🚀 Boost your Next.js development with this extension for VSCode. Streamline file generation and optimize your project's lifecycle. Easily craft pages, components, layouts, and more. Includes commands and snippets for Next.js, Prisma, tRPC, and key frameworks.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "21",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/8e956dbd-0a72-4d90-bf3a-d121a1fb68f3.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Wasp — Develop web apps in React & Node.js with no boilerplate",
        "description": "Wasp is the fastest way to develop full-stack web apps in React & Node.js. Describe high-level features (auth, CRUD, async jobs, …) via a simple config language, and write the rest of your logic in React, Node.js and Prisma. Wasp is currently in Beta.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "22",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/af8b2d00-edf6-4c74-a32f-a78efd6c1f89.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "ProseMirror — A toolkit for building rich-text editors on the web",
        "description": "ProseMirror is a toolkit for building rich-text editors on the web.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "23",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/5be8c1b8-f78d-4ca7-b76e-7951490ba063.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "CodeSandbox — Free, instant, collaborative sandboxes for rapid web development.",
        "description": "CodeSandbox is an online code editor and prototyping tool that makes creating and sharing web apps faster",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "24",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/80a26274-b44d-4470-bc62-a605dd5c79f3.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Bbedit — Leading professional HTML and text editor for macOS.",
        "description": "BBEdit is the leading professional HTML and text editor for macOS. This award-winning product has been crafted to serve the needs of writers, Web authors and software developers, and provides an abundance of features for editing, searching, and manipulation of prose, source code, and textual data.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "25",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/e464fdb2-04f0-45c1-ae0e-407f6887c5fb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Kotlin — Statically typed programming language targeting the Java /JS",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "26",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/f407ca6a-a6b6-4ab1-88c7-cf62e8114351.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "CodePen — Demo or it didn't happen.",
        "description": "CodePen is a social development environment for front-end designers and developers. Build and deploy a website, show off your work, build test cases to learn and debug, and find inspiration. CodePen is a playground for the front end side of the web. It's all about inspiration, education, and sharing.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "27",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/d837c665-999b-48c6-90be-38cdd03e5dac.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Wallaby — JS test runner in your code editor",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "28",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/2e6a0690-2115-4a71-bb08-ab9974a7062a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Tower – Git client for Mac and Windows — Build Better Software",
        "description": "Over 100,000 developers and designers are more productive with Tower - the most powerful Git client for Mac and Windows.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "29",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/5f621a68-2838-4ad2-97a5-fd3fc6dad117.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Replit — The fastest way to go from idea to production",
        "description": "An AI-powered software development & deployment platform for building, sharing, and shipping software fast.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "30",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/0c9d8a74-d6af-4869-b189-78d8b05bc9d8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Fork — A fast and friendly git client for Mac",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "31",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/91c03035-cf17-4622-aa9b-00ae9eef5bca.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Electron Forge — Quickly scaffold Electron projects with full build pipeline",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "32",
        "name": "",
        "imageUrl": null,
        "title": "SwiftShip — Build and Ship your iOS app in a few days or hours",
        "description": "A Swift UI Boilerplate that takes care of features commonly needed in mobile apps, and lets you save time and focus on your value proposition and main features. Save hours of development and ship your iOS app in a few days or hours.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "33",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/a6cbf976-1115-4721-bb03-071d2cba592c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Android Studio 2.0 — The official Google's Android IDE version 2.0",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "34",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/f85cffd0-9545-4a3d-b506-80e4066bd8de.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Turbo — Make Ship Happen",
        "description": "Turbo is an incremental bundler and build system optimized for JavaScript and TypeScript, written in Rust.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "35",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/da67b505-bae5-4fa9-b9d7-dbbb4a53196b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Atlassian Sourcetree — The best Mac and Windows client for Git and Mercurial.",
        "description": "A Git GUI that offers a visual representation of your repositories. Sourcetree is a free Git client for Windows and Mac.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "36",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/a35bc284-4813-440f-bd8d-c04bc08aaf18.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "CopilotForXcode — intitni/CopilotForXcode",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "37",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/f2913e7b-8ebc-4902-b0e8-e5d7bfdf0bba.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Xcode 16 — The newest developer tools from Apple",
        "description": "Apple empowers developers and fuels innovation with new tools and resources. Enhancements to Xcode and Swift, combined with new APIs, offer developers expanded capabilities for creating high‑quality apps.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "38",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/092e5e79-46ae-4713-8e8b-94d112d0b5e8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "npm — A package manager for javascript",
        "description": "Relied upon by more than 11 million developers worldwide, npm is committed to making JavaScript development elegant, productive, and safe. The free npm Registry has become the center of JavaScript code sharing, and with more than one million packages, the largest software registry in the world. Our other tools and services take the Registry, and the work you do around it, to the next level.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "39",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/01c5aa49-561d-4a2d-99c0-68568411433d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Javascript Tips — This is about one JS tip every day!",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "40",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/bfa93698-43a4-4fc6-94da-f42d5de9eb31.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Spacemacs — A community-driven Emacs distribution",
        "description": "Spacemacs is a new way to experience Emacs -- a sophisticated and polished set-up focused on ergonomics, mnemonics and consistency.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "41",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/127dfec6-4b04-424d-bed6-8fac6cafe67d.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "TinyMCE — Full featured web based JavaScript WYSIWYG HTML Editor",
        "description": "TinyMCE is a powerful and stable WYSIWYG HTML editor. It comes with more than 40 editing tools and premium features such as improved spell check, file management and upgraded copy-paste.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "42",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/8adc03ad-56f4-4460-80cd-a13363707f53.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "WebContainer API — Dev environments. In your web app.",
        "description": "From interactive tutorials to full-blown IDEs, build instant, interactive coding experiences backed by WebContainers: the trusted, browser-based runtime from StackBlitz. Run Node.js in your browser with unmatched speed and no remote VMs involved.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "43",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/f02335c0-f195-4e4f-aabd-e577cb8bdf1b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Dev Tools — Best Online web tools for developers",
        "description": "Your one stop destination for all developer utility tools including code generator tools, code converter tools, html code generator, css code generator, minifiers, seo tolls and many more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "44",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/49bf83f7-c10b-4d6e-b314-51140d7ed78a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Puter — A computer in your browser",
        "description": "A fun, approachable, playful environment where you can build and share apps",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "45",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/b7f66023-1b8e-496c-8d52-8a81950c49e7.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "RubyGems — Find, install, and publish RubyGems",
        "description": "The Ruby community’s gem hosting service. Instantly publish your gems and then install them. Use the API to find out more about available gems.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "46",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/d5a3a3fd-4a6c-40bf-a3df-f010714ee525.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Notepad++ — Notepad++ is a free source code editor / notepad replacement",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "47",
        "name": "",
        "imageUrl": "https://ph-files.imgix.net/7a48c2a7-5e08-4ce2-b19f-35fa7bbccf94.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "PhpStorm — The lightning-smart IDE for PHP programming by JetBrains",
        "description": "PhpStorm is a perfect PHP IDE for working with Symfony, Laravel, Drupal, WordPress, Laminas, Magento, Joomla!, CakePHP, Yii, and other frameworks.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }