{
    "url": "https://www.producthunt.com/categories/cloud-computing-platforms",
    "productCards": [
      {
        "rank": "1",
        "name": "Vercel",
        "icon": "https://ph-files.imgix.net/593ff5e2-9d11-491c-ab63-9e929e894214.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Vercel — Seamless hosting for frontend developers",
        "description": "Vercel is a platform for frontend developers to deploy and manage web applications efficiently. It offers serverless infrastructure and integrations with popular frameworks and tools, focusing on performance and scalability.",
        "productUrl":"https://www.producthunt.com/products/vercel/shoutouts",
        "websiteUrl":"https://vercel.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "Supabase",
        "icon": "https://ph-files.imgix.net/b9c546be-a73d-49be-84ac-92a774a5edfc.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Supabase — The open source Firebase alternative",
        "description": "Supabase is an open-source backend-as-a-service that provides real-time databases, authentication, and API services. It enables developers to build and scale applications quickly without managing server infrastructure.",
        "productUrl":"https://www.producthunt.com/products/supabase/shoutouts",
        "websiteUrl":"https://supabase.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/915790ab-c2f4-4659-8f38-30c4f271c3f5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/faf4390d-d95c-4de4-9368-e0375fb5103f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/9a382b91-86b9-4d4c-8277-3b79adfbf98e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "Firebase",
        "icon": "https://ph-files.imgix.net/cd6a3077-007d-4d68-a516-c8414b11bec8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Firebase — An app development platform backed by Google",
        "description": "An app development platform that helps you build and grow apps and games users love. Backed by Google and trusted by millions of businesses around the world.",
        "productUrl":"https://www.producthunt.com/products/firebase/shoutouts",
        "websiteUrl":"https://firebase.google.com/?utm_source=fabric&utm_medium=landing_page&utm_campaign=fabric_sunset&utm_content=get_fabric_io&ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/123f5a1b-97d4-4074-9e65-ab85c072c3b3.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/7d1f73af-b3c0-486d-bb36-047504427318.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/0c10372d-91e2-4129-8517-275eed50d1c8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "Google Cloud Platform",
        "icon": "https://ph-files.imgix.net/2df0eb38-7b7e-48a7-80d9-05c57b48d3d4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Google Cloud Platform — A suite of cloud computing services by Google",
        "description": "Build with generative AI, deploy apps fast, and analyze data in seconds with Google-grade security.",
        "productUrl":"https://www.producthunt.com/products/google-cloud-platform/shoutouts",
        "websiteUrl":"https://cloud.google.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/a0fc6d22-680e-4ec2-aa63-9012d5f3d1ed.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/a795af87-f9fb-418e-9869-a04a9372c1a8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/0f696b59-3b4b-4d33-9a5b-e18ea1314a3c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "DigitalOcean",
        "icon": "https://ph-files.imgix.net/db4ba1a3-da45-4435-b285-ca59047141e5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "DigitalOcean — A cloud platform to deploy, manage & scale apps of any size",
        "description": "Helping millions of developers easily build, test, manage, and scale applications of any size faster than ever before.",
        "productUrl":"https://www.producthunt.com/products/digitalocean/shoutouts",
        "websiteUrl":"https://digitalocean.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/c7bc122a-454c-4477-bd0a-a2daef1ec3a3.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/64b7d8f1-14ed-43c0-9693-79b2c9b970b6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/292697b5-9a68-447c-a94b-cc290ec6683d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "Render",
        "icon": "https://ph-files.imgix.net/c5755a02-777d-4baf-a7d0-c5654511ef36.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Render — Build, deploy, and scale your apps with unparalleled ease",
        "description": "A unified platform to build and run all your apps and websites with free SSL, a global CDN, private networks and auto deploys from Git.",
        "productUrl":"https://www.producthunt.com/products/render/shoutouts",
        "websiteUrl":"https://render.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/62aa34c2-bed6-4220-874d-edabeb1fea6e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/efbd3d37-8a34-4145-b787-4785e0dde195.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/108511e2-a6a3-4b48-9bfd-b8b08549a515.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "Ruby on Rails",
        "icon": "https://ph-files.imgix.net/dcd7544f-1c99-42be-be2b-e0cc80c463b0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ruby on Rails — A full-stack framework to build amazing web apps",
        "description": "Rendering HTML templates, updating databases, sending and receiving emails, maintaining live pages via WebSockets, enqueuing jobs for asynchronous work, storing uploads in the cloud, providing solid security protections for common attacks. Rails does it all and so much more.",
        "productUrl":"https://www.producthunt.com/products/ruby-on-rails/shoutouts",
        "websiteUrl":"http://rubyonrails.org/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "replicate",
        "icon": "https://ph-files.imgix.net/893eb4e0-61dd-4ee2-9f06-7db129d7582a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "replicate — source machine learning models with a cloud API",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/replicate-2/shoutouts",
        "websiteUrl":"https://replicate.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "Amazon Web Services",
        "icon": "https://ph-files.imgix.net/2244b16a-9d2e-4330-b432-3653fb1eb467.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Amazon Web Services — Virtual private server and web hosting-Amazon Lightsail",
        "description": "Amazon Lightsail is an easy-to-use virtual private server (VPS) that offers simple management of cloud resources such as containers, at low, predictable prices.",
        "productUrl":"https://www.producthunt.com/products/amazon-web-services-inc-9/shoutouts",
        "websiteUrl":"https://aws.amazon.com/lightsail?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "Upstash",
        "icon": "https://ph-files.imgix.net/bccabb30-bb51-4ab2-8247-49dd657c3362.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Upstash — Serverless data platform for Redis and Kafka",
        "description": "Serverless Redis and Kafka as a service with per request pricing. Use any Redis/Kafka clients. The built-in REST API enables use cases with serverless and edge functions.",
        "productUrl":"https://www.producthunt.com/products/upstash/shoutouts",
        "websiteUrl":"https://upstash.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/8a398f0f-06ee-48e5-9e1f-2d99e806a1d6.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/5e686fd9-b4be-4fea-a4b4-8d4b16512cd2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "VS Code",
        "icon": "https://ph-files.imgix.net/a32a6a01-1bfe-49df-b196-b9cc342c5175.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "VS Code — Microsoft Visual Studio Code lets you build and debug apps",
        "description": "Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications.",
        "productUrl":"https://www.producthunt.com/products/vs-code/shoutouts",
        "websiteUrl":"https://code.visualstudio.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/ff8f5f99-c225-42d4-b48f-fc757ef33dd5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/5bb27997-054a-4dfd-affb-81df11401667.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "AWS",
        "icon": "https://ph-files.imgix.net/67d208df-3f6c-4f9f-85cd-228ed4b45c8f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS — AWS offers reliable, scalable, and inexpensive cloud.",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/aws/shoutouts",
        "websiteUrl":"https://docs.aws.amazon.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "Cloudflare",
        "icon": "https://ph-files.imgix.net/ec7c42b6-ea2f-479b-96d1-c34cfa9b10b1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare — The web performance & security company",
        "description": "Cloudflare is a leading edge network services provider that offers a wide range of solutions to enhance the security, performance, and reliability of websites and applications. With its global network infrastructure and advanced technologies, Cloudflare empowers businesses to build a faster, more secure, and resilient online presence.",
        "productUrl":"https://www.producthunt.com/products/cloudflare/shoutouts",
        "websiteUrl":"http://www.cloudflare.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/a476f06a-5b71-48a7-b734-e4bf09ceb1ae.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/99a84c8b-1ee0-4d0f-9838-85ac702d0a27.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/f7bdd12a-8607-4954-80e9-5cbe580a7c88.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "Prisma",
        "icon": "https://ph-files.imgix.net/04da03de-e75f-4453-acf2-39ba73b7c2d0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Prisma — Turn your database into a GraphQL API",
        "description": "Prisma is a realtime GraphQL database layer. Connect directly from the frontend or build your own GraphQL server. - Compatible with existing tooling - Powerful GraphQL API - Runs everywhere",
        "productUrl":"https://www.producthunt.com/products/prisma-6/shoutouts",
        "websiteUrl":"https://www.prismagraphql.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/38341ca0-8d0b-4621-b7f4-574cdf4e9a23.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/e16d5cfa-c965-48bf-a493-cb8e378bf26e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/bbf39efb-e9b4-4147-8f3e-b2146b6810fa.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "Pinecone",
        "icon": "https://ph-files.imgix.net/6c80b7b1-050d-45b3-afad-2b94cdddbf01.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Pinecone — Long-term memory for AI",
        "description": "A vector database that makes it easy to build high-performance vector search applications. Developer-friendly, fully managed, and easily scalable without infrastructure hassles.",
        "productUrl":"https://www.producthunt.com/products/pinecone-2/shoutouts",
        "websiteUrl":"https://www.pinecone.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/57adc4ac-b282-4575-b248-dbf6d56fb76d.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/3a5ceef2-fc0b-4523-9cab-37037890a9d8.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/c8688054-17ca-4254-af66-09b82969c7f0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name": "PlanetScale",
        "icon": "https://ph-files.imgix.net/a34b17cd-6269-42b7-bd6f-8474f59fd6e7.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "PlanetScale — The ultimate MySQL database platform",
        "description": "A MySQL-compatible database that brings you scale, performance, and reliability without sacrificing developer experience.",
        "productUrl":"https://www.producthunt.com/products/planetscale/shoutouts",
        "websiteUrl":"https://planetscale.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name": "Appwrite",
        "icon": "https://ph-files.imgix.net/ea1c7b5e-0f17-46b4-aff7-64a9bbf538f1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Appwrite — 100% open source alternative for Firebase",
        "description": "A secure open-source backend server provides the core APIs required to build web and mobile applications. Appwrite provides authentication, database, storage, functions, messaging, and advanced realtime capabilities.",
        "productUrl":"https://www.producthunt.com/products/appwrite/shoutouts",
        "websiteUrl":"https://appwrite.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/d7ba06be-4f10-49c1-8d86-791130813952.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/53ccade7-8766-42c9-9e63-8a12093d8716.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/94aea52f-3550-4c12-a2c8-65ec8cf872ed.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name": "Netlify",
        "icon": "https://ph-files.imgix.net/76ab59d2-551c-4775-a162-f8490956d66f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Netlify — The composable platform for modern sites, stores, and apps.",
        "description": "Netlify is the foundation for Enterprises looking to modernize their web architecture. With Netlify, your team can ship faster, be more productive, reduce risk and complexity, and drive higher conversions and revenue. It features continuous deployment from Git across a global application delivery network, serverless form handling, support for AWS Lambda functions, and full integration with Let's Encrypt.",
        "productUrl":"https://www.producthunt.com/products/netlify/shoutouts",
        "websiteUrl":"https://www.netlify.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/d8d6109d-4f9a-4bc4-a79e-b3e49ef92385.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/4bfb7c04-fb37-42f0-8b8d-d0824124df07.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/0b73bc88-aff5-4f71-8d3f-57180a3649ce.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name": "Cloudflare Pages",
        "icon": "https://ph-files.imgix.net/7e4a4980-2139-420d-b490-62c9fe9a9270.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare Pages — Build Fast Sites. In Record Time.",
        "description": "Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites.",
        "productUrl":"https://www.producthunt.com/products/cloudflare-pages/shoutouts",
        "websiteUrl":"https://pages.cloudflare.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name": "AWS Lambda",
        "icon": "https://ph-files.imgix.net/a46e2608-8f72-4a89-82e0-abbe70f10f83.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS Lambda — An event-driven, serverless computing platform",
        "description": "A compute service that runs your code in response to events and automatically manages the compute resources, making it the fastest way to turn an idea into a modern, production, serverless applications.",
        "productUrl":"https://www.producthunt.com/products/aws-lambda/shoutouts",
        "websiteUrl":"https://aws.amazon.com/lambda?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "21",
        "name": "Xano",
        "icon": "https://ph-files.imgix.net/a3b86949-5fa9-466e-9f8a-dd09be37762e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Xano — The fastest way to build and deploy a scalable backend",
        "description": "Build a scalable backend for your app using no code. Transform, filter, and integrate with data from anywhere.",
        "productUrl":"https://www.producthunt.com/products/xano/shoutouts",
        "websiteUrl":"https://www.xano.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/bd667612-64fe-4eeb-9bec-11e550723d10.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/86b28937-6250-4cb0-b5c6-f35efe328030.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/5004a87a-2bed-4061-9229-2d59923502c6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "22",
        "name": "Telegram 4.7",
        "icon": "https://ph-files.imgix.net/ffb82f9d-697d-4b9f-8c05-5a5c34b39af5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Telegram 4.7 — Cloud-based, secure messaging app",
        "description": "Telegram Messenger is a globally accessible freemium, cross-platform, encrypted, cloud-based and centralized instant messaging service.",
        "productUrl":"https://www.producthunt.com/products/telegram-4-7/shoutouts",
        "websiteUrl":"https://itunes.apple.com/app/telegram-messenger/id686449807?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "23",
        "name": "Modal",
        "icon": "https://ph-files.imgix.net/8e6f4db6-6438-4413-b6d5-e3b9a560c438.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Modal — The serverless platform for AI, ML & data teams.",
        "description": "Run or deploy machine learning models, massively parallel compute jobs, task queues, web apps, and much more, without your own infrastructure.",
        "productUrl":"https://www.producthunt.com/products/modal/shoutouts",
        "websiteUrl":"https://modal.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/e3913002-ad9e-4cc2-968b-fd4ad977113b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/a5b014aa-5b6c-46d6-8836-9e8e96d050fe.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/599d166b-d134-4576-8c05-46c94d407ccf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "24",
        "name": "vscode.dev",
        "icon": "https://ph-files.imgix.net/0643ccd3-579d-4a56-bdbb-17e68793ab86.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "vscode.dev — Bringing VS Code to the browser",
        "description": "Now when you go to https://vscode.dev, you'll be presented with a lightweight version of VS Code running fully in the browser. Open a folder on your local machine and start coding. No install required.",
        "productUrl":"https://www.producthunt.com/products/vscode-dev/shoutouts",
        "websiteUrl":"https://vscode.dev/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/4cffaa77-c923-4ea5-af70-b7f275c5b36f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/435023d3-9580-4741-b974-a5fcccf98f1b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/715793cc-f92d-4152-82fb-0fff058e23c3.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "25",
        "name": "Hasura",
        "icon": "https://ph-files.imgix.net/abd04bbd-8c76-464e-bdc3-77b5e80e0649.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Hasura — Instant GraphQL on all your data",
        "description": "Hasura helps developers and organisations build and ship modern applications & APIs faster by making data instantly accessible over a realtime GraphQL & REST APIs.",
        "productUrl":"https://www.producthunt.com/products/hasura/shoutouts",
        "websiteUrl":"https://hasura.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/c76c5ce6-3425-4b71-89cd-76819ab2da18.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/bbbd04e0-432b-4998-89d5-7cddef06ae70.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/81cc14f7-335c-46e2-92b5-ead012996a3b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "26",
        "name": "DataBricks",
        "icon": "https://ph-files.imgix.net/ac301ed1-8308-469d-841b-2eb5765021eb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "DataBricks — Simplify big data and AI",
        "description": "Databricks’ mission is to accelerate innovation for its customers by unifying Data Science, Engineering and Business. Founded by the team who created Apache Spark, Databricks provides a Unified Analytics Platform for data science teams to collaborate with data engineering and lines of business to build data products.",
        "productUrl":"https://www.producthunt.com/products/databricks/shoutouts",
        "websiteUrl":"https://databricks.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/a17b228f-bf28-4cb4-89e3-4c509dc932db.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/31c7e24b-6206-4ece-9bb3-50a587e530a7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/a22f69f4-e23a-4bad-ba79-b634766b0aa6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "27",
        "name": "Neon",
        "icon": "https://ph-files.imgix.net/eab801a9-fe40-4f01-a30d-37472d9bc2e0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Neon — Serverless Postgres: Now Generally Available",
        "description": "Neon reimagines Postgres with a serverless architecture. With a generous free tier, scale-to-zero, and true database branching. Copy data and schema in a second and scale resources automatically. Ideal for developers prioritizing scalability and performance.",
        "productUrl":"https://www.producthunt.com/products/neon-6/shoutouts",
        "websiteUrl":"https://neon.tech/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/1e2ea28b-1643-4858-b711-1adf59b7a4d9.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "28",
        "name": "Microsoft Azure",
        "icon": "https://ph-files.imgix.net/0a107993-4052-4863-9870-aa687814c4cf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Microsoft Azure — Cloud Computing Services",
        "description": "Invent with purpose, realize cost savings, and make your organization more efficient with Microsoft Azure’s open and flexible cloud computing platform.",
        "productUrl":"https://www.producthunt.com/products/microsoft-azure-2/shoutouts",
        "websiteUrl":"https://azure.microsoft.com/en-us?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "29",
        "name": "Weaviate",
        "icon": "https://ph-files.imgix.net/cebcb818-90c0-494a-965f-c0a08c4511ef.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Weaviate — The AI-native database for a new generation of software",
        "description": "The AI-native database for a new generation of software. Store and retrieve data objects and vector embeddings. Seamlessly connect to your favorite ML models. And build intuitive, reliable AI applications that scale.",
        "productUrl":"https://www.producthunt.com/products/weaviate/shoutouts",
        "websiteUrl":"https://weaviate.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/adfa7633-b420-40f0-a941-326ef2b149ed.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/d549e046-490c-4c59-9944-c74919ce9d87.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/3cc4a9ac-fc52-4d1c-8a8d-beef25eb6cc4.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "30",
        "name": "AWS Amplify",
        "icon": "https://ph-files.imgix.net/d9b33649-d11f-4464-aa5d-3f2e43bc7e24.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS Amplify — JavaScript library for app development using cloud services",
        "description": "AWS Amplify provides a declarative and easy-to-use API for cloud operations. You can build cloud-powered web and mobile experiences with AWS Amplify and goes well with any JavaScript based frontend library.",
        "productUrl":"https://www.producthunt.com/products/aws-amplify/shoutouts",
        "websiteUrl":"https://aws.github.io/aws-amplify?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/5b4829aa-b545-45f5-a76e-8a2353a635c4.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/7c6215bf-d869-49d9-9548-f52820ad1e76.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/e878743e-d501-4f0f-8db0-da6cd7b468f1.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "31",
        "name": "Sentry",
        "icon": "https://ph-files.imgix.net/197f2704-229a-4a91-b9d7-10364042b31e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sentry — Application monitoring and error tracking software",
        "description": "Self-hosted and cloud-based application monitoring that helps software teams see clearer, solve quicker, & learn continuously.",
        "productUrl":"https://www.producthunt.com/products/sentry/shoutouts",
        "websiteUrl":"http://www.sentry.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/4b5c0dc1-d0f6-4fce-beba-56d519866ab0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/187cdf2c-5fa6-49b2-974e-c199aba6ab5e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/e16862d1-176e-40f6-aefd-e614a97f5297.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "32",
        "name": "AwS Activate",
        "icon": "https://ph-files.imgix.net/eb11eb6c-ee5e-412b-8ae1-0afbd85c7b12.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS Activate — coupons: $5,000 in credits 2 years and others deals Dec 23",
        "description": "AWS Activate is a comprehensive program designed to support startups and businesses and provide them with the resources and tools they need to build and scale their businesses on the Amazon Web Services (AWS) cloud platform.",
        "productUrl":"https://www.producthunt.com/products/aws-activate/shoutouts",
        "websiteUrl":"https://1kb.link/e5fe6?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/80520f41-60dc-43d0-8a3d-68e2474ba018.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/b9854487-35c0-43a7-a60c-e33fd5d313f1.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/97648582-f5e1-483a-be74-5948144f3842.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "33",
        "name": "NestJS",
        "icon": "https://ph-files.imgix.net/37abd321-bdbe-4e17-bb77-e97b9ed20842.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "NestJS — Building efficient, reliable and server-side applications.",
        "description": "NestJS is a framework for building efficient, scalable Node.js web applications. It uses modern JavaScript, is built with TypeScript and combines elements of OOP (Object Oriented Progamming), FP (Functional Programming), and FRP (Functional Reactive Pr...",
        "productUrl":"https://www.producthunt.com/products/nestjs/shoutouts",
        "websiteUrl":"https://nestjs.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/856d7036-2c2b-4463-9e64-26315865721d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/4c4a98ad-4b8f-4d4f-92ce-7fa440178352.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/1e701598-927e-45df-936b-2e666843e0e4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "34",
        "name": "Docker",
        "icon": "https://ph-files.imgix.net/32c58a09-b2a0-4669-ab9e-d31ce9e44ff1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Docker — Accelerate how you build, share, and run applications",
        "description": "Build, share, run, and verify applications anywhere without tedious environment configuration or management.",
        "productUrl":"https://www.producthunt.com/products/docker/shoutouts",
        "websiteUrl":"https://www.docker.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "35",
        "name": "Infisical",
        "icon": "https://ph-files.imgix.net/2ac7c08f-c516-447a-9439-759ffb4fe184.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Infisical — Helping dev teams sync environment variables",
        "description": "A simple, end-to-end encrypted platform that enables Node.js teams to sync and manage their environment variables. Developers can modify start/dev scripts to pull and inject environment variables into local environments with 1 line of code.",
        "productUrl":"https://www.producthunt.com/products/infisical/shoutouts",
        "websiteUrl":"https://infisical.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/002590a8-b72c-435e-b566-52d64949382a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/10677d06-b7d4-47c9-bfb7-def676e0e128.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/a8bff529-611a-4295-92f2-520ac85a68b2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "36",
        "name": "Cloudflare Vectorize",
        "icon": "https://ph-files.imgix.net/c9931fda-0158-439a-b48f-bbc9ed1a5ddc.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare Vectorize · Vectorize v1 — Fast, efficient vector database on the edge.",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/cloudflare-vectorize-vectorize-v1/shoutouts",
        "websiteUrl":"https://developers.cloudflare.com/vectorize?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "37",
        "name": "Svix",
        "icon": "https://ph-files.imgix.net/e7891aa5-d7bc-4241-82d5-60bffa53d148.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Svix — Webhooks as a service",
        "description": "Build a secure, reliable, and scalable webhook sending platform",
        "productUrl":"https://www.producthunt.com/products/svix/shoutouts",
        "websiteUrl":"https://www.svix.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/eb838fa3-5590-4457-9c2f-b50e1c200195.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/4e8a4d2a-9c27-44e3-a0c3-19259cac89de.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/a437ba07-b074-4313-87aa-ff03d55ae8dc.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "38",
        "name": "QuickNode",
        "icon": "https://ph-files.imgix.net/67782944-2d34-4058-b46d-d64dd92c1f24.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "QuickNode — The Blockchain development platform",
        "description": "A Web3 infrastructure platform helping developers & businesses build, launch, and scale blockchain-powered applications.",
        "productUrl":"https://www.producthunt.com/products/quicknode/shoutouts",
        "websiteUrl":"https://quicknode.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/f54ef9ae-9251-45da-bee1-5b8a295f596f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/a6a75526-d0ff-46e1-91ec-f4b147e6d556.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/b0c8e29a-41b9-4b45-8c3c-350b24055191.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "39",
        "name": "Depot",
        "icon": "https://ph-files.imgix.net/11849dfd-97aa-4d7f-a945-f47e05ecc783.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Depot — Build Docker containers up to 20x faster",
        "description": "Depot is a hosted container build service that builds Docker images up to 20x faster than existing CI providers. We run fully managed Intel and Arm builders in AWS, accessible directly from CI and from your terminal.",
        "productUrl":"https://www.producthunt.com/products/depot-3/shoutouts",
        "websiteUrl":"https://depot.dev/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/21e82763-ff0b-4d94-a7ab-588f035ee9ab.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/f5ae4921-0a87-4016-8bd0-6bb59bf3a621.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/29851960-012f-4b9a-9352-c390704fa70a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "40",
        "name": "Lark",
        "icon": "https://ph-files.imgix.net/17261807-4635-4fd2-ad56-2c3f5c79b56d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Lark — The simplest way to create and collaborate",
        "description": "Lark combines a multitude of essential collaboration tools in a single interconnected platform, including Chat, Calendar, Creation and Cloud storage. These functions are always in sync, and are easy access from one to the next.",
        "productUrl":"https://www.producthunt.com/products/lark-3/shoutouts",
        "websiteUrl":"https://www.larksuite.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/095cbbdf-9656-4380-b248-ed47b2382d69.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/bea7ef1b-5570-41fd-a6cb-2ed016e2c9ae.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/6c56f740-cd82-4f6b-a15f-0b6d7698b0a4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "41",
        "name": "Airbyte",
        "icon": "https://ph-files.imgix.net/2e9f665f-0ebf-48ff-a480-fbc6f2fde304.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Airbyte — Open-source data integration",
        "description": "An open-source data integration platform to build ELT pipelines. Consolidate your data in your data warehouses, lakes and databases.",
        "productUrl":"https://www.producthunt.com/products/airbyte/shoutouts",
        "websiteUrl":"https://airbyte.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/e04063c5-3831-4fee-bebc-836dce409a6c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/72d8a992-b548-4e95-bd8e-af824eafc1a4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/eb021f61-f48d-44a8-9bf7-3fc4d0832a3e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "42",
        "name": "Cloudflare Workers",
        "icon": "https://ph-files.imgix.net/976e559c-bfdc-4f4d-8b4a-a934e7aa81ea.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare Workers — Your site. Our network.",
        "description": "Build blazing fast websites by seamlessly deploying static assets alongside your APIs and application code.",
        "productUrl":"https://www.producthunt.com/products/cloudflare-workers/shoutouts",
        "websiteUrl":"https://workers.cloudflare.com/sites?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/768f8a24-c17e-4ffb-a762-51ae805fa985.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/13050551-9e85-4c1f-9389-69c3d28d869f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "43",
        "name": "NVIDIA",
        "icon": "https://ph-files.imgix.net/bdfc0b1d-7a68-4664-a7f8-1268b628cd3b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "NVIDIA — The official handle for NVIDIA.",
        "description": "NVIDIA, inventor of the GPU, which creates interactive graphics on laptops, workstations, mobile devices, notebooks, PCs, and more. We created the world’s largest gaming platform and the world’s fastest supercomputer. We are the brains of self-driving cars, intelligent machines, and IoT.",
        "productUrl":"https://www.producthunt.com/products/nvidia/shoutouts",
        "websiteUrl":"http://www.nvidia.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/d180afa8-cb04-4554-8a9b-bd59934ba59f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "44",
        "name": "MacOS",
        "icon": "https://ph-files.imgix.net/f0a7c9b5-c8ca-4149-bd4a-36c61a810bd8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "MacOS — The operating system from Apple",
        "description": "macOS (previously Mac OS X and later OS X) is a series of proprietary graphical operating systems developed and marketed by Apple Inc. since 2001. It is the primary operating system for Apple's Mac computers. Within the market of desktop, laptop and home computers, and by web usage, it is the second most widely used desktop OS, after Microsoft Windows.",
        "productUrl":"https://www.producthunt.com/products/macos/shoutouts",
        "websiteUrl":"https://www.apple.com/macos?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/a80b128b-07d0-44e0-abfa-6a19e5871eac.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/862554ec-3df8-434c-81ce-057c8f0f63e8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/6d87b066-0c0a-40a2-ae46-00b7a572ec2b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "45",
        "name": "Coolify",
        "icon": "https://ph-files.imgix.net/a5603809-a9ce-447b-b3e6-f7279015e2e2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Coolify — An open-source & self-hostable Heroku / Netlify alternative.",
        "description": "Coolify is an open-source and self-hostable all-in-one (IaaS) solution to host your applications, databases, or other open-source services. It's an alternative software to Heroku and Netlify and other similar software out there.",
        "productUrl":"https://www.producthunt.com/products/coolify/shoutouts",
        "websiteUrl":"https://coolify.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/7b533ce7-84d2-46a7-a6f4-665dcff2c2be.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/0be83c76-21d5-46a0-b217-a967c71b920f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/90915ab1-efd7-47f1-9473-f15cf866266f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "46",
        "name": "Scaleway",
        "icon": "https://ph-files.imgix.net/b5939df2-c084-40a9-bcb2-f70311e84a41.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Scaleway — The cloud of choice",
        "description": "Build, deploy and scale applications on Europe's most complete cloud ecosystem.",
        "productUrl":"https://www.producthunt.com/products/scaleway-3/shoutouts",
        "websiteUrl":"https://www.scaleway.com/en?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "47",
        "name": "Apple Silicon",
        "icon": "https://ph-files.imgix.net/7d14b963-beed-4f24-a8ef-4390312c179e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Apple Silicon — Custom silicon for Mac & iPhone designed by Apple Inc.",
        "description": "https://www.producthunt.com/products/apple-silicon/shoutouts",
        "productUrl":"https://developer.apple.com/documentation/apple-silicon?ref=producthunt",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "48",
        "name": "SigNoz",
        "icon": "https://ph-files.imgix.net/08993f1c-3b07-4966-97e9-f6be1ddd44be.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "SigNoz — Open source alternative to Datadog",
        "description": "SigNoz is an open-source alternative to DataDog. We help developers find issues in the software they run on cloud and solve them quickly. Run SigNoz in your infrastructure and get your application monitoring setup at 10x lower cost",
        "productUrl":"https://www.producthunt.com/products/signoz/shoutouts",
        "websiteUrl":"https://signoz.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/4aed3ed2-117a-490e-bc1d-1bc4c8aca716.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/a87ac560-a1e2-4c3b-b2a2-825f87c67ccb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/3319ffdd-556f-4610-9489-0c0fd2f8c369.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "49",
        "name": "StackBlitz",
        "icon": "https://ph-files.imgix.net/5d5f3851-a353-4bce-abb1-1bf326ef5c74.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "StackBlitz — StackBlitz is an instant fullstack web IDE for the JavaScript ecosystem.",
        "description": "StackBlitz is an instant fullstack web IDE for the JavaScript ecosystem. It's powered by WebContainers, the first WebAssembly-based operating system which boots Node.js environment in milliseconds, securely within your browser tab.",
        "productUrl":"https://www.producthunt.com/products/stackblitz/shoutouts",
        "websiteUrl":"https://stackblitz.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/61ccdd2a-2914-47d8-9cb8-e52697ce441a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "50",
        "name": "Buf",
        "icon": "https://ph-files.imgix.net/93fde99f-43bd-4474-8f05-affec4292d47.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Buf — A new way of working with Protocol Buffers",
        "description": "Your organization should not have to reinvent the wheel to use Protobuf efficiently and effectively. Stop worrying about your Protobuf management strategy getting out of control. We'll handle that for you, so you can worry about what matters.",
        "productUrl":"https://www.producthunt.com/products/buf/shoutouts",
        "websiteUrl":"https://buf.build/docs/introduction?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/e7471962-7daa-46ec-855d-eb78ff7c250e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/cd99eab1-7b17-4058-8802-56a4861fbbea.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/f984790e-474b-473b-9125-3e0e76dd5ae6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "51",
        "name": "Heroku",
        "icon": "https://ph-files.imgix.net/ea6235a6-f6d2-459c-b9e8-31dd8fe6498d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Heroku — Provides services & tools to build, run, mobile applications",
        "description": "Heroku is a platform as a service (PaaS) that enables developers to build, run, and operate applications entirely in the cloud.",
        "productUrl":"https://www.producthunt.com/products/heroku/shoutouts",
        "websiteUrl":"https://www.heroku.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/3ea0bf5d-e4fd-4af8-b495-c4011eba29f4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/aa4d2f7d-6ced-467c-b392-13e9036cfc7f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/570f0e18-4833-4654-867b-66f478d27a5c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "52",
        "name": "Railway",
        "icon": "https://ph-files.imgix.net/b0388730-3bb2-40ac-bd95-4c936088f44e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Railway — Railway is an infrastructure platform",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/railway-2/shoutouts",
        "websiteUrl":"https://railway.app/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "53",
        "name": "Fly.io",
        "icon": "https://ph-files.imgix.net/c893ecf5-beb3-431d-9857-ff773cb3d8b4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Fly.io — Launch Apps Near Users",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/fly-io/shoutouts",
        "websiteUrl":"https://fly.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "54",
        "name": "Snowflake",
        "icon": "https://ph-files.imgix.net/f7a93a5f-1c5c-4d52-bf5f-d9c69cf3b8e7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Snowflake — Snowflake Data Cloud",
        "description": "Join the Data Cloud to unify multiple data workloads, easily discover & securely share live governed data, democratize data analytics & more.",
        "productUrl":"https://www.producthunt.com/products/snowflake-3/shoutouts",
        "websiteUrl":"https://www.snowflake.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "55",
        "name": "kubernates",
        "icon": "https://ph-files.imgix.net/7264f5f0-69b4-42a9-ba47-e63a0f715c61.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "kubernetes — Google's open-source version of container cluster management",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/kubernetes/shoutouts",
        "websiteUrl":"http://kubernetes.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "56",
        "name": "TensorFlow",
        "icon": "https://ph-files.imgix.net/f9b89eda-07db-4e65-9807-cd8247ee3124.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "TensorFlow — An end-to-end open source machine learning platform",
        "description": "TensorFlow is a fast, flexible, and scalable open-source machine learning library for research and production.",
        "productUrl":"https://www.producthunt.com/products/tensorflow/shoutouts",
        "websiteUrl":"http://tensorflow.org/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "57",
        "name": "PosketBase",
        "icon": "https://ph-files.imgix.net/1cc74777-81bd-43eb-8601-1dcf05e99be0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "PocketBase — Open Source realtime backend in 1 file",
        "description": "PocketBase is an open source Go backend that has embedded realtime database, files and users management, admin UI and REST-ish API, all compiled in 1 portable file. Think of it as a lightweight alternative to Firebase or Supabase.",
        "productUrl":"https://www.producthunt.com/products/pocketbase/shoutouts",
        "websiteUrl":"https://pocketbase.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/295934f6-98e4-4230-bcb1-5d3923e771bb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/bdea3cc2-8038-4873-82ba-8b9ead8cd82f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/f2e6476a-cb43-42aa-a8b1-fd6620234558.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "58",
        "name": "NixoS",
        "icon": "https://ph-files.imgix.net/bd43291e-557a-4a92-a46c-669d638985d2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "NixOS — Reproducible builds and deployments.",
        "description": "Nix is a tool that takes a unique approach to package management and system configuration. Learn how to make reproducible, declarative and reliable systems.",
        "productUrl":"https://www.producthunt.com/products/nixos/shoutouts",
        "websiteUrl":"https://nixos.org/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "59",
        "name": "Microsoft Azure",
        "icon": "https://ph-files.imgix.net/3d746381-c526-429a-8b75-5297e297d499.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Microsoft Azure — Optimize your costs by developing in the cloud.",
        "description": "Optimize your costs by developing in the cloud. Invent with purpose.",
        "productUrl":"https://www.producthunt.com/products/microsoft-azure/shoutouts",
        "websiteUrl":"https://azure.microsoft.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/52a461c2-fd99-47ea-bf12-09bb4cfba1df.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/8017c83d-65d1-4279-97bd-0925a094b3c9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/99dc5f96-0b0c-4971-aa71-b80a962e4a59.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "60",
        "name": "Logtail",
        "icon": "https://ph-files.imgix.net/a573e8b1-8b56-4bbb-990d-633549c153d0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Logtail — Query your logs like you query your database",
        "description": "ClickHouse-based SQL-compatible log management. Log more, pay less.",
        "productUrl":"https://www.producthunt.com/products/logtail/shoutouts",
        "websiteUrl":"https://logtail.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/6b431097-064e-4e04-b593-5cc38dd1dfd4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/5143a4d0-204a-4260-8c5e-a9933c451107.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/b77220f8-c1a6-42fa-8878-81ad4ed4f9a8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "61",
        "name": "Alchemy",
        "icon": "https://ph-files.imgix.net/5c8f5d8d-a956-43aa-bc27-92b65b388d13.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Alchemy Supernode — The Industry Leading Ethereum API",
        "description": "Alchemy Supernode is the most widely used Ethereum API with all the functionality of a node, incl. full JSON-RPC support. The Web 3 infrastructure engine of Alchemy Supernode delivers 99% reliability, dynamic scalability, and 100% data correctness.",
        "productUrl":"https://www.producthunt.com/products/alchemy-supernode/shoutouts",
        "websiteUrl":"https://alchemyapi.io/supernode?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/69c41d41-c704-4d72-8fa5-ec60c9edb11c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/e08ac926-0cc6-44e6-bbe6-18eb55e5bc7a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/ddf83164-9a32-42fd-ae9f-e84c15ac0a87.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "62",
        "name": "Ubuntu",
        "icon": "https://ph-files.imgix.net/a988f207-a6ff-46b5-ad16-444177f33ca9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ubuntu — Linux for human beings",
        "description": "Ubuntu (/ʊˈbʊntuː/ uu-BUUN-too) is a free and open-source Linux distribution based on Debian.",
        "productUrl":"https://www.producthunt.com/products/ubuntu/shoutouts",
        "websiteUrl":"https://ubuntu.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "63",
        "name": "WebAssembly",
        "icon": "https://ph-files.imgix.net/bac1ffd4-e56d-4042-b550-7934bbf34eb4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "WebAssembly — New binary format for compiling applications for the web",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/webassembly/shoutouts",
        "websiteUrl":"https://webassembly.org/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "64",
        "name": "ElasticSearch",
        "icon": "https://ph-files.imgix.net/7f4cf8c2-9440-472a-829b-ac29790e6a5f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "ElasticSearch — Lucene based search server.",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/elasticsearch/shoutouts",
        "websiteUrl":"https://www.elastic.co/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "65",
        "name": "ScreenshotOne",
        "icon": "https://ph-files.imgix.net/10e7ef30-f2ed-482f-a5e9-d55de252202d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "ScreenshotOne — The Screenshot API you can finally rely on.",
        "description": "Render websites and HTML as images. Block cookie banners and ads. The API uses the latest Google Chrome for rendering and Google Cloud Platform for performance and scalability.",
        "productUrl":"https://www.producthunt.com/products/screenshotone/shoutouts",
        "websiteUrl":"https://screenshotone.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/29631ddf-874c-4449-bcd5-3c9324f72aa5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/20212f42-29a0-4e72-b87d-05c6eae70341.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/8588a653-2b6b-40c6-a782-ee2c533d92bf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "66",
        "name": "Porter",
        "icon": "https://ph-files.imgix.net/42fe4fbb-8537-45c2-bfbd-8e2961bf4525.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Porter — PaaS you cannot outgrow",
        "description": "Porter brings the magical experience of deploying an application with just a few clicks into your own AWS or GCP account. Porter will manage the underlying infrastructure for you - simply point at your repo and Porter will handle the rest, from building your application to autoscaling it.",
        "productUrl":"https://www.producthunt.com/products/porter-3/shoutouts",
        "websiteUrl":"https://github.com/porter-dev/porter?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/dc908749-030e-4123-8182-8f290d17b5d2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/7f93d996-436f-47d2-bca6-d239334279c8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/1cfa30b5-2020-4e85-b9d6-4325e8a245b6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "67",
        "name": "IPFS",
        "icon": "https://ph-files.imgix.net/170f96a0-3c47-4052-888a-7abade73aeda.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "IPFS — Powers the distributed web",
        "description": "The InterPlanetary File System is a protocol and peer-to-peer network for storing and sharing data in a distributed file system.",
        "productUrl":"https://www.producthunt.com/products/ipfs/shoutouts",
        "websiteUrl":"https://ipfs.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "68",
        "name": "Hatchbox",
        "icon": "https://ph-files.imgix.net/f612d983-443f-461c-912b-a7593238f057.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Hatchbox — We'll take care of everything for you.",
        "description": "Hatch is way for you to deploy Rails apps to your own servers at places like Digital Ocean as easily as Heroku. We'll take care of installing Ruby, Nginx, PostgreSQL, Redis and more and even manage environment variables and all the other little details for you.",
        "productUrl":"https://www.producthunt.com/products/hatchbox/shoutouts",
        "websiteUrl":"https://www.hatchbox.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "69",
        "name": "Flixier",
        "icon": "https://ph-files.imgix.net/7942d461-ebda-4607-9f35-64b71fff1561.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Flixier — Create and publish videos faster than ever",
        "description": "Flixier Pro online video editor improves your workflow with 1 minute rendering on any device, streamlined collaboration and plenty of cloud storage.",
        "productUrl":"https://www.producthunt.com/products/flixier/shoutouts",
        "websiteUrl":"https://flixier.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/a9135fae-2fa7-468e-b5ca-8df77d6bb0b7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/0df99112-6d1b-48d6-863d-04a7ff6f0a36.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/3218c645-0f0e-4b34-9aa6-69806c8b2561.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "70",
        "name": "MotherDuck",
        "icon": "https://ph-files.imgix.net/5fd2a535-a102-4627-b3d5-790ea06ffd6f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "MotherDuck — The ducking simple data warehouse for analytics",
        "description": "The cloud SQL analytics platform that helps you do more with your data. A unique architecture enables dual query execution across local machines and the cloud, letting you experience smooth workflows and ultra-efficient performance that won’t break the bank.",
        "productUrl":"https://www.producthunt.com/products/motherduck/shoutouts",
        "websiteUrl":"https://motherduck.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/e9d5d33b-e697-40dd-84c9-7178dd7d5403.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/6248b47c-19ec-498a-b62d-698133aa47cd.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/f8a0900a-22ea-4bca-afe3-dc2c39dda84f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "71",
        "name": "Flightcontrol",
        "icon": "https://ph-files.imgix.net/450f63b2-68bf-4035-a56f-2fb799e3040c.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Flightcontrol — Developer-first AWS Infrastructure",
        "description": "Designed for teams that want the benefits & reliability of AWS without hiring devops",
        "productUrl":"https://www.producthunt.com/products/flightcontrol/shoutouts",
        "websiteUrl":"https://www.flightcontrol.dev/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/c81e4fe4-8e9f-4f75-a817-af79a454a833.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/d2bfc93f-eadb-439a-a377-b07797c548c0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/82c0d12e-01e2-48e4-86f7-a6d86ca1f891.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "72",
        "name": "Appliku",
        "icon": "https://ph-files.imgix.net/dda07729-1f67-4e64-98fb-9f85789326c8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Appliku — Deploy your app project in 5 minutes on your own server",
        "description": "Appliku automagically sets up your server and runs your web apps from GitHub or GitLab. Set up in under 5 minutes, click to deploy. Think of Appliku as your personal DevOps.",
        "productUrl":"https://www.producthunt.com/products/appliku/shoutouts",
        "websiteUrl":"https://appliku.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/8a0d2db4-fbfd-4837-8425-9576767e6303.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "73",
        "name": "twilio",
        "icon": "https://ph-files.imgix.net/161e59aa-e2ef-425a-b636-bbdce6569172.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "twilio — Build the future of communications",
        "description": "Twilio is a cloud communications platform as a service company based in San Francisco, California.Twilio powers the future of business communications. Enabling phones, VoIP, and messaging to be embedded into web, desktop, and mobile software.",
        "productUrl":"https://www.producthunt.com/products/twilio/shoutouts",
        "websiteUrl":"http://www.twilio.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/fe6f6075-78e0-4c52-8ae4-0f56a6f2146e.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/20880aba-f21a-448a-9612-9f071c9349e9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/429944d7-79f5-42d0-9fc7-d4346113084a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "74",
        "name": "bunny.net",
        "icon": "https://ph-files.imgix.net/b055b4c8-49e9-43b2-be5d-e4a66e9055cf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "bunny.net — The content delivery platform that truly hops.",
        "description": "Experience performance like never before. bunny.net is a reliable, powerful and lightning fast CDN designed to offer incredible performance at the worlds most cost-effective pricing. Join over 100.000 websites and make your website as fast as a bunny!",
        "productUrl":"https://www.producthunt.com/products/bunny-net/shoutouts",
        "websiteUrl":"https://bunny.net/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/8f23a97d-255c-4b78-83d1-d501e8957a15.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/9e6143de-1c5e-41ba-839f-e6b6f1902db2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/29cff94a-3f6b-4b85-83f3-00813a764cbb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "75",
        "name": "Cleavr.io",
        "icon": "https://ph-files.imgix.net/b5c9dfe8-676a-43a4-8677-8ed8bc40ced8.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cleavr.io — Carve out a slice of the cloud and serve your apps",
        "description": "Connect Cleavr to your favorite VPS hosting provider, provision servers, and deploy your apps with ease. Avoid doing all of the work yourself. With Cleavr, it just takes a few clicks to ship your apps.",
        "productUrl":"https://www.producthunt.com/products/cleavr-io/shoutouts",
        "websiteUrl":"https://cleavr.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/63ada83a-43df-4984-8277-1ccf2f669881.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/eea8bc22-32da-4e1f-b0f8-b4ecd7f74568.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/482555d6-5005-4cf4-8e2b-58f3c6a208bb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "76",
        "name": "Amazon Web Services",
        "icon": "https://ph-files.imgix.net/b062477d-6325-4598-84cb-bd921810bdcb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Amazon Web Services, Inc. — Amazon Simple Email Service | Cloud Email Service | Amazon Web Services",
        "description": "Amazon Simple Email Service (SES) is a cost-effective, flexible, and scalable email service that enables developers to send mail from within any application.",
        "productUrl":"https://www.producthunt.com/products/amazon-web-services-inc-2/shoutouts",
        "websiteUrl":"https://aws.amazon.com/ses?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "77",
        "name": "Cloudways",
        "icon": "https://ph-files.imgix.net/39c5d11b-4033-4ca1-88ef-3aadf4be9ddd.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudways — Your Managed Cloud Hosting Platform",
        "description": "Managed cloud hosting platform that empowers your business by facilitating choice, simplicity and performance. All this is backed by caring expert support.",
        "productUrl":"https://www.producthunt.com/products/cloudways/shoutouts",
        "websiteUrl":"http://www.cloudways.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/bcf8aa10-9650-4c30-be38-f79046e0eab8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/a53f6178-8c9c-43d2-a878-794b1824abe9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/2d07ec62-900f-4021-9617-d2d5f9971683.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "78",
        "name": "Dfinity",
        "icon": "https://ph-files.imgix.net/dfa94bd6-27a2-4af0-b729-e2606d9defdf.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Dfinity — Build On The Internet. No Dependencies.",
        "description": "The Internet Computer extends the public Internet so it can natively host websites, software systems, open internet services and DeFi. It is created by independent data centers worldwide running the ICP protocol.",
        "productUrl":"https://www.producthunt.com/products/dfinity/shoutouts",
        "websiteUrl":"https://dfinity.org/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "79",
        "name": "Val Town",
        "icon": "https://ph-files.imgix.net/30687d08-5d93-4729-aac3-acc6ede03a0f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Val Town — If GitHub Gists could run and AWS Lambda were fun.",
        "description": "If GitHub Gists could run and AWS Lambda were fun.",
        "productUrl":"https://www.producthunt.com/products/val-town/shoutouts",
        "websiteUrl":"https://val.town/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/27db9f0f-1819-42b8-a47a-d5704f4ceb31.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/e9efa84c-8cd0-4be6-bc00-1c0b3937ed23.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/676e38cb-b38a-48ac-bbda-672afe1016b1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "80",
        "name": "Doppler",
        "icon": "https://ph-files.imgix.net/5568900d-a099-4d0a-a268-dd7192f29037.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Doppler — Easily manage your environment variables and secrets",
        "description": "Doppler is the multi-cloud SecretOps Platform developers and security teams trust to provide secrets management at enterprise scale. Seamlessly manage and secure application secrets across cloud, environments, and team members.",
        "productUrl":"https://www.producthunt.com/products/doppler-2/shoutouts",
        "websiteUrl":"https://doppler.com/partners/product-hunt?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/39bb9561-a247-40ae-ac90-e3cb22b3d4c7.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/d9d49e15-c0bc-46a5-9deb-033b84fed729.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/5274dc89-6bfd-42fc-827e-ebe03cced937.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "81",
        "name": "Linode",
        "icon": "https://ph-files.imgix.net/81f09ac5-7cc1-409e-97a5-7400dd06da4c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Linode — Instantly deploy an VPS",
        "description": "Linode, LLC is an American cloud hosting subsidiary of Akamai Technologies that provides virtual private servers. It is based in Philadelphia, Pennsylvania.",
        "productUrl":"https://www.producthunt.com/products/linode/shoutouts",
        "websiteUrl":"https://linode.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/4a013238-317c-43f3-934e-da78ee44e29a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/7584ff34-f6f8-4bff-bd8a-a4335f3897a9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/9ac3ed2b-4f47-4728-b807-8b8337789323.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "82",
        "name": "llama cloud",
        "icon": "https://ph-files.imgix.net/a20d6e50-6094-4f87-bad7-6426e3e18fc4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "llama cloud — The platform for LlamaIndex",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/llama-cloud/shoutouts",
        "websiteUrl":"https://cloud.llamaindex.ai/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "83",
        "name": "Gadget",
        "icon": "https://ph-files.imgix.net/cf942563-41e3-4591-a6eb-3c7f738a135b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Gadget — The fastest way to build and run web apps",
        "description": "Gadget is a full-stack, serverless JavaScript platform for web app developers who want to build faster and maintain less. Skip the boilerplate features, repetitive code, and busywork, and get your ideas out the door in hours.",
        "productUrl":"https://www.producthunt.com/products/gadget-2/shoutouts",
        "websiteUrl":"https://gadget.dev/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/3b4afa3a-d574-4f75-b517-96adaafac36f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/d0690523-0632-46fc-9b3e-99eb665e8485.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/68bbcab7-4dfb-4f0f-9591-d16d43acffc3.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "84",
        "name": "WebContainer API",
        "icon": "https://ph-files.imgix.net/8adc03ad-56f4-4460-80cd-a13363707f53.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "WebContainer API — Dev environments. In your web app.",
        "description": "From interactive tutorials to full-blown IDEs, build instant, interactive coding experiences backed by WebContainers: the trusted, browser-based runtime from StackBlitz. Run Node.js in your browser with unmatched speed and no remote VMs involved.",
        "productUrl":"https://www.producthunt.com/products/webcontainer-api/shoutouts",
        "websiteUrl":"https://webcontainers.io/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/7384ae6e-6abe-469b-ac15-4efe2c89016b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/ffbd57da-f7eb-4bc2-9c57-a0ee3731fd6e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/723d928e-0802-4c85-bbef-305218d6ebec.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "85",
        "name": "Ably Realtime",
        "icon": "https://ph-files.imgix.net/37163ea5-c081-481d-bb35-6313273c5019.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ably Realtime — Build realtime features you can trust to deliver at scale",
        "description": "Ably is a pub/sub messaging platform with a suite of integrated services to deliver complete realtime functionality directly to end-users. Everyday we guarantee low latency delivery of billions of messages to more than 50 million devices over a secure, reliable, and highly available global edge network.",
        "productUrl":"https://www.producthunt.com/products/ably-realtime/shoutouts",
        "websiteUrl":"https://www.ably.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/541457d1-a5b0-4820-aeee-e917486dee65.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/8120247d-3dc5-4145-ae03-652da3ec172a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/ad2a3f74-b383-402f-b85d-1e70bb250a68.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "86",
        "name": "RunPod",
        "icon": "https://ph-files.imgix.net/7e0316a5-3a00-4628-8140-b33928162262.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "RunPod — On demand GPU Cloud, scale ML inference with Serverless",
        "description": "",
        "productUrl":"https://www.producthunt.com/products/runpod/shoutouts",
        "websiteUrl":"https://runpod.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "87",
        "name": "QEMU",
        "icon": "https://ph-files.imgix.net/2e222fa3-97cf-4363-8323-06f3a3820e19.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "QEMU — A generic & open source machine emulator & virtualizer.",
        "description": "QEMU: the FAST! processor emulator Full-system emulation - Run operating systems for any machine, on any supported architecture User-mode emulation - Run programs for another Linux/BSD target, on any supported architecture Virtualization - Run KVM, Xen Virtual",
        "productUrl":"https://www.producthunt.com/products/qemu/shoutouts",
        "websiteUrl":"https://www.qemu.org/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/b2a39d3c-2817-4d56-8ba8-90fef096fc4c.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/2c3feee9-c120-4cdf-9dac-81233a661178.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/a2899e32-4426-477c-8bc0-44292c32dca8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "88",
        "name": "Cyberduck",
        "icon": "https://ph-files.imgix.net/8c8f501e-3773-446c-94c1-fc73f2f1568c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cyberduck — Libre server and cloud storage browser for Mac and Microsoft",
        "description": "Libre FTP, SFTP, WebDAV, Amazon S3, OpenStack Swift, Backblaze B2, Microsoft Azure & OneDrive, Google Drive and Dropbox browser for Mac and Windows.",
        "productUrl":"https://www.producthunt.com/products/cyberduck/shoutouts",
        "websiteUrl":"https://cyberduck.io/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "89",
        "name": "fortrabbit",
        "icon": "https://ph-files.imgix.net/374c7f29-3a25-4bce-843c-99b1f5032fb1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "fortrabbit — PHP as a Service — tweets by @o_stark and others",
        "description": "fortrabbit is PHP as a service. A cloud computing platform for PHP developers.",
        "productUrl":"https://www.producthunt.com/products/fortrabbit/shoutouts",
        "websiteUrl":"http://www.fortrabbit.com/?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "90",
        "name": "Keyv",
        "icon": "https://ph-files.imgix.net/5d417e13-b5dc-47c3-bb7e-b658275e9e92.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Keyv — Simple key-value storage with multiple backend support",
        "description": "Keyv is a simple key-value interface for JavaScript oriented for storing any kind of data, anywhere. It supports MySQL, PostgreSQL, SQLite, Redis, Mongo, DynamoDB, Firestore, Memcached, and more",
        "productUrl":"https://www.producthunt.com/products/keyv/shoutouts",
        "websiteUrl":"https://keyvhq.js.org/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/59236501-77b0-4369-96b5-281baac77ae7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/8bff9f94-2216-4fe2-b708-c674dccd4943.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/af08ec33-721e-4a4e-af31-e760b7ff8b59.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "91",
        "name": "OVHcloud Partner Program",
        "icon": "https://ph-files.imgix.net/253e6f57-665d-4dbf-b788-d874ecf50c11.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "OVHcloud Partner Program — Supports for partners in reaching their business objectives",
        "description": "OVHcloud Partner Program is available in all countries. Aimed at those who are eager to recommend their OVHcloud based solutions as value-added resellers, & managed service providers, in areas like integration, added solutions, & consulting/training companies.",
        "productUrl":"https://www.producthunt.com/products/ovhcloud-partner-program/shoutouts",
        "websiteUrl":"https://partner.ovhcloud.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/10f591c4-0022-473b-bf6b-9d20ae499438.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/c06349fa-180c-404d-8d95-44fa75415dd8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"https://ph-files.imgix.net/e1efbc75-4771-485f-aeab-c1f07e2f0b1f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "videoUrl": ""
      },
      {
        "rank": "92",
        "name": "Datadog, Inc",
        "icon": "https://ph-files.imgix.net/99b25702-dd13-48d7-8ebd-33051d0c40d3.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Datadog, Inc. — Monitoring and security platform for cloud applications",
        "description": "Datadog is a monitoring service for cloud-scale applications, providing monitoring of servers, databases, tools, and services, through a SaaS-based data analytics platform.",
        "productUrl":"https://www.producthunt.com/products/datadog-inc/shoutouts",
        "websiteUrl":"https://www.datadoghq.com/?ref=producthunt",
        "imageUrl1":"https://ph-files.imgix.net/7952824c-efd0-4117-8150-bebce64418f1.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl2":"https://ph-files.imgix.net/218c3afc-2d30-4fc3-8c14-3ecd990a16c6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=256&h=160&fit=crop",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "93",
        "name": "AWS S3 Tool",
        "icon": "https://ph-files.imgix.net/d760d4d9-74ad-4f01-ba0a-0f4596b1f296.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS S3 Tool — Manage AWS S3 Buckets",
        "description": "Amazon S3 or Amazon Simple Storage Service is a service offered by Amazon Web Services that provides object storage. Manage your AWS S3 buckets. AWS S3 Tool has following features: - With Amazon Web Services (AWS) S3 profiles manage S3 buckets easily - Delete Files from S3 buckets - Download Files from S3 buckets - Upload Files to S3 Buckets https://www.youtube.com/watch?v=2fQKEpt9_S4",
        "productUrl":"https://www.producthunt.com/products/aws-s3-tool/shoutouts",
        "websiteUrl":"https://www.microsoft.com/store/p/aws-s3-tool/9p6q0xr4gmgg?ref=producthunt",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }