{
    "url": "https://www.producthunt.com/categories/static-site-generators",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/7d6535a4-c2fe-4f75-a71e-e5bd5156b0c9.x-icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "ShipFast — Ship your startup in days, not weeks",
        "description": "The NextJS boilerplate with all the stuff you need to get your product in front of customers. From idea to production in 5 minutes.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/53213ebd-6c42-4ec4-839a-8d40a4206354.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Vite — Next Generation Frontend Tooling",
        "description": "Vite is a build tool that aims to provide a faster and leaner development experience for modern web projects. A dev server that provides rich feature enhancements. A build command that bundles your code, pre-configured to output highly optimized static assets.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/cf32e935-a497-4745-8430-8644aaf27107.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Nuxt — The Vue framework for web architects",
        "description": "An open source framework to create performant and production-grade full-stack web apps and websites with confidence.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/7e4a4980-2139-420d-b490-62c9fe9a9270.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare Pages — Build Fast Sites. In Record Time.",
        "description": "Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/7773976d-e914-4046-91b1-154f91680d94.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Shipixen — Create a blog & landing page in minutes",
        "description": "Create a production-ready landing page & blog with your branding, theme & pages. You get the code & an SEO-optimized website so you can focus on building, not setting up.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/976e559c-bfdc-4f4d-8b4a-a934e7aa81ea.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare Workers — Your site. Our network.",
        "description": "Build blazing fast websites by seamlessly deploying static assets alongside your APIs and application code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/6bad3f69-e994-422a-b532-569cbb4ee076.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Astro — The web framework that scales with you.",
        "description": "Build fast content-driven websites, powerful SPA web applications, dynamic server APIs and everything in-between.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/d4ffdc41-1157-4e2f-a02e-c9cfda4acfb6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Eleventy — A simpler static site generator.",
        "description": "A simpler static site generator. An alternative to Jekyll. Written in JavaScript. Transforms a directory of templates (of varying types) into HTML. Works with HTML, Markdown, JavaScript, Liquid, Nunjucks, Handlebars, Mustache, EJS, Haml, and Pug.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "icon": null,
        "title": "BoilerBay — Launch your dream project 10x faster",
        "description": "The NextJS Starter Kit with everything you need to ship your product in days, not weeks. From idea to production 10x Faster.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/069dd336-4c9b-4450-bdc9-304e7c5681b2.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Startup Idea Tester — Test your idea in days not months",
        "description": "Startup Idea Tester is here to revolutionize the way you validate your business ideas. Designed for founders with a lot of ideas, this powerful boilerplate allows you to focus on the marketing aspects and starting getting quickly emails with a waitlist system.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/c07ea694-1fca-46b2-8c11-60bf5f92892d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Github Pages — Websites for you and your projects.",
        "description": "Build your own site from scratch or generate one for your project. You get one site per GitHub account and organization, and unlimited project sites. Let‘s get started.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/c2e65732-fd75-4f17-bdaf-1e8932467a21.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Quasar Framework — performance, responsive websites, PWA, SSR",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/1c6953e7-5544-4ac7-ba46-1ae7e8106728.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Hugo — Hugo - the extension you really want!",
        "description": "A Chrome Extension that enhances your browsing experience for Hugo. Right now, the basic features allow you to see when a website you're visiting has been built with Hugo as well as search the Hugo Docs from your Omnibox (address) Bar.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/915c41a4-365e-4bea-a4dc-eb586f3d8cf1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Docusaurus — Easy to maintain open source documentation websites",
        "description": "Docusaurus helps you ship a top-notch documentation site in no time! Focus on your content: just write Markdown files! Put your site online in 5 minutes, then customize it. Full-featured: plugins, themes, search, blog, versioning, i18n, React...",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }