{
    "url": "https://www.producthunt.com/categories/website-analytics",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/0329497e-75f9-4fcc-8dae-5b279bcb56e8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "PostHog — The open source product OS",
        "description": "Open-source product analytics, session recording, feature flagging and A/B testing that you can self-host. Everything engineers need to build better products.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/6859e0cb-5118-4c0f-82d4-3c54bd4d7621.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Mixpanel — Event analytics everyone can use",
        "description": "An event analytics platform that allows anyone to get answers from their customer and revenue data in seconds. It offers powerful real-time charts and visualizations of how people interact with your digital products and company.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/84db18d0-6f62-4d19-8afa-968ee4bc6751.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Plausible Analytics — Simple analytics for your website",
        "description": "A privacy focused, open source alternative to Google Analytics that lets you measure your traffic and gives you 100% data ownership.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/9f2fd64e-a608-46a9-9755-053e646f89b0.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "June — The Simple Product Analytics App",
        "description": "June is product analytics for B2B SaaS. Get auto-generated reports focused on how companies use your product, not users",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/9c06d78c-6a07-429b-b750-b91eed907a8a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "FullStory — Craft a more perfect digital experience",
        "description": "FullStory is your digital experience analytics platform for on-the-fly funnels, pixel-perfect replay, custom events, heat maps, advanced search, Dev Tools, and more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/6536ab0a-00d3-4a66-af88-9438a4315831.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "UptimeRobot — Downtime Happens. Get Notified!",
        "description": "An uptime monitoring service that helps users to get acknowledged of the downtimes of their websites/servers and also track the performance of them. It is actively used by 600,000+ users with much more number of monitors being checked regularly.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/2456a1eb-af9b-4032-9c28-45e7724cd2c0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Google Analytics — Get essential customer insights.",
        "description": "Google Analytics is a comprehensive web analytics tool offered by Google that provides valuable insights into the performance and behavior of websites, mobile apps, and other digital platforms. It allows businesses and website owners to track and analyze a wide range of data, enabling them to make informed decisions and optimize their online presence.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/98e776ed-70e6-4294-bb2b-ef1dcf4f2896.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "umami — A self-hosted alternative to Google Analytics",
        "description": "Umami is a simple, easy to use, self-hosted web analytics solution. The goal is to provide you with a friendlier, privacy-focused alternative to Google Analytics and a free, open-sourced alternative to paid solutions.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "icon": "https://ph-files.imgix.net/b4426700-71f2-459e-87f3-206f3b9f6471.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Metricool — Analyze, manage and measure your digital content",
        "description": "All in one site: web analytics, blog content, Twitter, Facebook, Instagram, publication planner, real-time and more. The ultimate tool for analysing, managing and measuring the success of all your digital content and campaigns. Free of charge. Complete. Intuitive.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/b055b4c8-49e9-43b2-be5d-e4a66e9055cf.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "bunny.net — The content delivery platform that truly hops.",
        "description": "Experience performance like never before. bunny.net is a reliable, powerful and lightning fast CDN designed to offer incredible performance at the worlds most cost-effective pricing. Join over 100.000 websites and make your website as fast as a bunny!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/37e6cecb-760f-45e6-95e0-b1a5dbd1f1d4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Hotjar — For digital experiences people love",
        "description": "Hotjar’s visual insights, user feedback, and live interviews show you what site visitors do, and why they do it. Access all the insights you need in one place and join 1.1 million websites in 180+ countries who already use Hotjar to turn their clicks into conversions. Install a single script and get started for free.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/f026c8ee-75a2-44de-afa4-684be5c68bdc.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ugly Duckling — Consistency on 𝕏 made easier.",
        "description": "Ugly Duckling is a simple and affordable analytics tool that helps you stay consistent and grow on X. The first version of Ugly Duckling, a Chrome extension, received a warm reception from the community and garnered over 100 daily active users now makes a comeback as a web application with new sharing features, beautiful charts and community leaderboard.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/dfc42ba5-f9af-4955-9b94-2b0751d94e7e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Simple Analytics — Simple, clean, and privacy-friendly analytics 📊",
        "description": "Simple Analytics gives you the analytics you need without invading the privacy of your users, with a clean interface, and simple integration.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/83c688b3-4ae6-486f-9b2e-38ef46a026e7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "TelemetryDeck — Lightweight analytics that's not evil",
        "description": "TelemetryDeck is a service that helps app and web developers improve their product by supplying immediate, accurate analytics data while users use your app. And the best part: It's all anonymized so your users' data stays private!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "",
        "icon": "https://ph-files.imgix.net/55f5f7f7-3869-4ea4-baf8-70db45cc4b9b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Fathom Analytics — Simple and private website analytics.",
        "description": "Fathom is a simple, light-weight, privacy-focused alternative to Google Analytics. So, stop scrolling through pages of reports and collecting gobs of personal data about your visitors, both of which you probably don’t need. Our website stats show up on a single, blazingly fast dashboard so you can make business decisions quickly.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }