{
    "url": "https://www.producthunt.com/categories/no-code-platforms",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/22023c3a-52cf-4320-b181-0b5894fc03ab.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Framer — Design and ship your dream site with zero code",
        "description": "A no-code platform to create responsive webpages with text, links, media, and incredible animations.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/f6dcab85-5195-4a2b-ae33-7fee00608298.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Webflow — Create custom, responsive websites, visually",
        "description": "Take control of HTML, CSS, and JavaScript in a visual canvas. Webflow generates clean, semantic code that’s ready to publish or hand to developers.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/9e0ee9b4-d147-4c63-9061-79061baa28f9.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Bubble — Build web apps without code, entirely visually",
        "description": "Design, develop, and launch production-grade applications without code",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/d4ad8bb6-7bd5-4e3c-93af-b69c553312ed.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Expo — An open-source platform for building native apps",
        "description": "Build, deploy, and quickly iterate on native Android, iOS, and web apps from the same JavaScript codebase.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/9acdbce2-d993-489b-b6e3-afb817d04d0b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Zapier — Connect your apps and automate workflows",
        "description": "Easy automation for busy people. Zapier empowers you to automate your work across 5,000+ apps—so you can move forward, faster.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/e58c5131-a65f-4287-aa49-b2fb3d105870.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cycle — Your feedback hub, on autopilot",
        "description": "Cycle is the fastest way for your team to capture product feedback and share customer insights - without the busywork 👉 https://www.cycle.app",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/9ee3d8b4-2c11-42d8-8020-1295e23ce929.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "FlutterFlow — Build cross-platform mobile apps visually",
        "description": "Create beautiful UI, generate clean code, and deploy to the app stores or web in one click. Fully extensible with custom code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/a3b86949-5fa9-466e-9f8a-dd09be37762e.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Xano — The fastest way to build and deploy a scalable backend",
        "description": "Build a scalable backend for your app using no code. Transform, filter, and integrate with data from anywhere.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "icon": "https://ph-files.imgix.net/d9b33649-d11f-4464-aa5d-3f2e43bc7e24.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "AWS Amplify — JavaScript library for app development using cloud services",
        "description": "AWS Amplify provides a declarative and easy-to-use API for cloud operations. You can build cloud-powered web and mobile experiences with AWS Amplify and goes well with any JavaScript based frontend library.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/c6155af3-d909-4a4c-8226-894275d1bb7e.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Retool — Build internal tools, remarkably fast",
        "description": "An application development platform that enables developers to combine the benefits of traditional software development with a drag-and-drop UI editor and AI to build internal tools radically faster. Deploy it anywhere, connect to any internal service, import your libraries, debug with your toolchain, and share it securely to users to ensure good and well-governed software by default.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/72dfe2ac-646f-44a8-9a6d-5d8097ccc835.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Albato — A no-code platform for all automations",
        "description": "Integrate your applications into automated workflows using a no code builder.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/9b89dafe-b565-431d-9093-23e626ae286a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "MindPal — Build AI agents for your tasks, with your data",
        "description": "Build customized ChatGPT-like agents that understand both your standards and your business context in seconds with no code — anything from a customer support chatbot, an internal AI search engine, to a full-scale CEO assistant.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/33bbc115-24f5-4c27-adb2-ef011c50b576.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Make — Design, build and automate your work",
        "description": "A visual platform for anyone to design, build, and automate anything—from tasks and workflows to apps and systems—without coding.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/3f03bdd9-7d1c-49a6-850a-4ec844fdc9ea.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "ToDesktop — Convert your web app to a desktop app in 2 minutes",
        "description": "Take your web app codebase and transform it into a cross platform desktop app with native functionality.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "",
        "icon": "https://ph-files.imgix.net/24a944d4-ad23-4fcc-93a6-018fad330b9f.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Dokin — Sync live data from apps in Sheets, Slides, and Docs",
        "description": "Connect marketing channels, CRMs, and databases to Google Sheets and Looker with no-code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name": "",
        "icon": "https://ph-files.imgix.net/78eabb8b-7ef3-4bbb-98f0-e6cadb155b09.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Relay.app — The new standard for automation",
        "description": "Relay.app is the easiest-to-use Zapier alternative that lets you automate workflows with powerful AI and Human-in-the-Loop features.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name": "",
        "icon": "https://ph-files.imgix.net/fcde694f-6982-4d00-864c-a3c180203ab6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Memberstack — Authentication & Payments for Webflow. Total design freedom.",
        "description": "Memberstack empowers you to build anything - from gated blogs, to social media platforms - all using Memberstack & Webflow (or, whatever else you use to build sites & apps). Over 3,000 companies like Slack, Reddit, and American Airlines use Memberstack to build scalable, custom membership experiences. You can build everything you need without coding - but, you can also incorporate your own code into your projects and scale with Memberstack to a full-blown react application.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name": "",
        "icon": "https://ph-files.imgix.net/e27da880-1b85-4171-b086-f9bd9d30a9fb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Dora AI — Generate sites using AI",
        "description": "A text-to-website tool that generates landing pages with natural language, using a powerful no-code editor.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name": "",
        "icon": "https://ph-files.imgix.net/5a6c6c6a-21a5-4b76-8264-55fc7f92cacb.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Momentum Page — Launch your landing page in seconds. Get users in minutes.",
        "description": "Page is a stupid-simple no-code landing page builder, that allows you to launch page in seconds, use social media to grow your views, get your signups, message them and eventually sell. It's free if you build in public.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name": "",
        "icon": "https://ph-files.imgix.net/8cbc145a-5abf-456c-bd2d-2576b74a6c0d.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Super — Create Websites with Notion",
        "description": "Create a website in less than a minute that’s easy to manage and looks great, with instant page loads, SEO optimization, and no-code. All your content stays in Notion so you can focus on creating while Super handles the rest.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "21",
        "name": "",
        "icon": "https://ph-files.imgix.net/99901859-6f81-4d81-b7a0-40dce2644641.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Fibery — Product discovery & development platform",
        "description": "Fibery is a product discovery and development platform. Analyze user feedback, identify top insights, track development, and close the feedback loop.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "22",
        "name": "",
        "icon": "https://ph-files.imgix.net/8c7b16db-c6c1-4695-a26e-7c9baca30f95.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Weavely — Build web forms with custom UX and UI from Figma designs",
        "description": "Build web forms that stand out with custom UX and UI, without coding. The Weavely form builder enables you to design and publish forms directly in Figma. Get creative with form design, apply conditional logic and reuse brand assets to collect more responses.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "23",
        "name": "",
        "icon": "https://ph-files.imgix.net/90963a5e-69fe-4850-ad44-5adc313a9542.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Wized — Design your web application in Webflow, build it with Wized",
        "description": "\"The no-code tool the Webflow community has been waiting for.\" Wized enables you to build 100% custom web applications on top of your Webflow projects.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "24",
        "name": "",
        "icon": "https://ph-files.imgix.net/bf707a85-fbbd-4beb-85cc-ec056f488cf8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Fillout.com — Make any form in minutes",
        "description": "Fillout is a powerful, no-code form builder. Create a form in minutes and style the form to match your brand. Add multiple pages, powerful conditional logic, and 40+ customizable question types.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "25",
        "name": "",
        "icon": "https://ph-files.imgix.net/ad938778-e017-4ecd-9d5c-b5a3c87733d8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Designmodo — No-code email template and website builders.",
        "description": "Designmodo is an all-in-one solution to create website and email newsletter designs that impress and engage your audience. Create your email templates and websites 20x faster, with no design limitations and no need for coding skills. Postcards email buidler provides you with all the tools necessary to start building and customizing your email template - from scratch to the finished product in just a few minutes. Collaborate with the entire team to bring ideas to the table from everyone.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "26",
        "name": "",
        "icon": "https://ph-files.imgix.net/1343b5b2-1fce-4c5a-a9c7-7dc7f8f227b9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Tally — The simplest way to create forms",
        "description": "A simple, yet powerful form builder that allows you to create any type of form without breaking the bank.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "27",
        "name": "",
        "icon": "https://ph-files.imgix.net/2091e6bf-0283-4318-aa54-13b89e8f0737.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Gradio — Simply create and share a UI for your machine learning model",
        "description": "The fastest way to demo your machine learning model with a friendly web interface so that anyone can use it, anywhere.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "28",
        "name": "",
        "icon": "https://ph-files.imgix.net/ec714738-1a69-4821-ac8d-af4eff63d4d4.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Airtable — The perfect tool to stay organized",
        "description": "Airtable is a platform that makes it easy to build powerful, custom applications. These tools can streamline just about any process, workflow, or project—and best of all, you can build them without ever learning to write a single line of code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "29",
        "name": "",
        "icon": "https://ph-files.imgix.net/3349e30d-93f8-4737-afe9-327e95ac8f5a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "supastarter — A SaaS starter kit",
        "description": "Production-ready starter kits and templates to save time.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "30",
        "name": "",
        "icon": "https://ph-files.imgix.net/deecbb94-38a6-43da-8dd8-305ea9e54974.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Softr — Build custom apps powered by your data, no code required.",
        "description": "Softr turns your spreadsheets (Airtable, Google Sheets) and databases into customer portals, internal tools, and any other custom app. Pick a template or start from scratch.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "31",
        "name": "",
        "icon": "https://ph-files.imgix.net/c5021d06-66b4-4fcc-b8ee-a3f4c862fb67.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "n8n — Workflow automation for technical people",
        "description": "n8n is a source-available workflow automation tool designed for technical users. Our low-code platform offers a seamless blend of code and an intuitive interface, serving as the perfect bridge between engineers and other people at your organization.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "32",
        "name": "",
        "icon": "https://ph-files.imgix.net/cd4263bb-796c-4829-905a-a350ccb6bbf7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Dopt — The product-led growth platform for modern teams",
        "description": "Use our pre-built React components, flexible SDKs, and powerful platform to effortlessly build better product onboarding, assistance, and announcements. Free for companies with under 1,000 monthly users.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "33",
        "name": "",
        "icon": "https://ph-files.imgix.net/f834fbaa-7d81-4fb6-a447-5027c80fe12f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "SaaS AI — The fastest way to launch your AI SaaS",
        "description": "SaaS AI: The Only Next.js Starter Kit Tailored for AI Web-Apps. Designed to streamline your development process, it eliminates weeks of work, empowering you to concentrate on delivering the features that matter most.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "34",
        "name": "",
        "icon": "https://ph-files.imgix.net/8d4fa480-49f1-4da1-aa57-aaa65db6a0b0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Typedream — No-code site builder, easy as Notion, pretty as Webflow",
        "description": "Everything you need to build your website in record time. Simple to design and manage with no-code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "35",
        "name": "",
        "icon": "https://ph-files.imgix.net/fc85ecb8-e629-43da-af6e-6f3393d7d9d9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Reform — Clean-looking, on-brand forms, no code required",
        "description": "Clean-looking, on-brand forms that are easy to use in your no-code projects, send out in emails, or put on your website. A modern form builder for your tool belt.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "36",
        "name": "",
        "icon": "https://ph-files.imgix.net/8e956dbd-0a72-4d90-bf3a-d121a1fb68f3.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Wasp — Develop web apps in React & Node.js with no boilerplate",
        "description": "Wasp is the fastest way to develop full-stack web apps in React & Node.js. Describe high-level features (auth, CRUD, async jobs, …) via a simple config language, and write the rest of your logic in React, Node.js and Prisma. Wasp is currently in Beta.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "37",
        "name": "",
        "icon": "https://ph-files.imgix.net/3c56dfe3-3138-4dfb-be07-6c4b036c3187.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "mevo — create chatbots easily",
        "description": "mevo is an easy-to-use no-code chatbot builder that comes with scripted and AI-powered options, lots of templates, shareable chatbot pages, and more. Create a chatbot, share or place it on your web page, and get notified when someone interacts with it.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "38",
        "name": "",
        "icon": "https://ph-files.imgix.net/094c98e9-fe64-45d2-9457-34f406f03b8f.x-icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Wordware (YC S24) — web-hosted IDE for building AI agents",
        "description": "Wordware is a web-hosted IDE for LLM orchestration, enabling cross-functional teams to build AI applications. Serving as an LLM backend, it functions like a new programming language, based on English but merging concepts like loops, logic, and function calling",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "39",
        "name": "",
        "icon": "https://ph-files.imgix.net/850480b2-9b0d-4045-bfa6-d46ff1cf2c76.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ionic Framework — Cross-platform mobile app development",
        "description": "Ionic is a complete open-source SDK for hybrid mobile app development created by Max Lynch, Ben Sperry, and Adam Bradley of Drifty Co.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "40",
        "name": "",
        "icon": "https://ph-files.imgix.net/c2963758-f210-4e02-a3a2-b57c542f9841.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Text Blaze — Eliminate repetitive typing and mistakes.",
        "description": "Easy-to-use templates with endless customizability and powerful automation. All with full control at your fingertips.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "41",
        "name": "",
        "icon": "https://ph-files.imgix.net/ea4a0d07-c204-46b0-aa9e-5b180e0af8e9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sheety — Turn your Google Sheet into an API instantly, for free",
        "description": "Turn any Google sheet into an API instantly, for free. Power websites, apps, or whatever you like, all from a spreadsheet. Changes to your spreadsheet update your API in realtime.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "42",
        "name": "",
        "icon": null,
        "title": "Told — Collect user feedback with in-product surveys",
        "description": "A no-code survey tool that helps you collect user or customer feedback and understand your data simply.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "43",
        "name": "",
        "icon": "https://ph-files.imgix.net/814d5f70-be1a-43cb-a33b-87d550f999a9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Coze — The easiest way to build AI bots",
        "description": "Coze is a no-code AI bot builder. Whether you have coding experience or not, you can quickly turn your bot ideas into reality. Build powerful bots powered by Large Language Models, and publish them to various messaging apps like Discord, Telegram or Slack.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "44",
        "name": "",
        "icon": "https://ph-files.imgix.net/d4ffdc41-1157-4e2f-a02e-c9cfda4acfb6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Eleventy — A simpler static site generator.",
        "description": "A simpler static site generator. An alternative to Jekyll. Written in JavaScript. Transforms a directory of templates (of varying types) into HTML. Works with HTML, Markdown, JavaScript, Liquid, Nunjucks, Handlebars, Mustache, EJS, Haml, and Pug.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "45",
        "name": "",
        "icon": "https://ph-files.imgix.net/71409bbb-a3d4-4e09-81d1-f20b328a7385.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Glide — Create an app from a Google Sheet in five minutes",
        "description": "Glide turns spreadsheets into beautiful, easy-to-use apps, without code. Pick a spreadsheet or start with a template, customize your app, then share it instantly with anyone. Start today for free!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "46",
        "name": "",
        "icon": null,
        "title": "BoilerBay — Launch your dream project 10x faster",
        "description": "The NextJS Starter Kit with everything you need to ship your product in days, not weeks. From idea to production 10x Faster.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "47",
        "name": "",
        "icon": "https://ph-files.imgix.net/6a77e0da-ac55-4f02-91f9-cd4fc2c6ed1d.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Pipedream — Connect APIs, remarkably fast.",
        "description": "Pipedream is an integration platform for developers, with over 800k customers across 10k companies. Our customers use Pipedream to build automation between over 2000 integrated applications today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "48",
        "name": "",
        "icon": "https://ph-files.imgix.net/004a389d-7182-484c-bde9-e34461c4fc21.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Chameleon — Boost Product Engagement",
        "description": "Create and publish user onboarding, product tours and tooltips without engineering. Chameleon allows you to create beautiful product guidance that helps, guides, and delights your users throughout their journey.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "49",
        "name": "",
        "icon": null,
        "title": "Streamlit — Turn python scripts into beautiful ML tools",
        "description": "Streamlit lets you create apps for your machine learning projects with deceptively simple Python scripts. Prototype quickly with hot-reloading, so your app updates live as you edit and save your file. Try it now: ⬇️ $pip install streamlit $streamlit hello",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "50",
        "name": "",
        "icon": "https://ph-files.imgix.net/2dcacc76-6e98-4c8f-bee0-4d7d83fb1aa6.vnd.microsoft.icon?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Directus — Instant no-code app and dynamic API for any SQL database",
        "description": "The Modern Data Stack 🐰 — Directus is an instant REST+GraphQL API and intuitive no-code data collaboration app for any SQL database.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "51",
        "name": "",
        "icon": "https://ph-files.imgix.net/18b4b5af-0507-4ace-869d-bbee1b8e0ab6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Redwood JS — The app framework for startups",
        "description": "Full-stack, multi-client JavaScript Framework built on React, GraphQL, and Prisma",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "52",
        "name": "",
        "icon": "https://ph-files.imgix.net/33ea6c5c-575b-4ac1-adf4-11a978ea444d.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Novel — Open-source Notion-style editor with AI autocomplete",
        "description": "Novel is an open-source Notion-style WYSYWIG editor with AI-powered autocompletions ✨ Built with Next.js Tiptap, OpenAI, and the Vercel AI SDK: https://sdk.vercel.ai/docs",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "53",
        "name": "",
        "icon": "https://ph-files.imgix.net/40789696-36ff-42e5-86e7-406b110e5e47.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Glide — Build Beautiful Apps Without Programming",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "54",
        "name": "",
        "icon": "https://ph-files.imgix.net/27d299a5-4ebb-4cdb-acce-f4462541a38f.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "EarlyBird Beta — Build a landing page and validate your new idea in 10 mins.",
        "description": "EarlyBird is a no-code landing page builder for creatives to build, pitch, and validate their business ideas. The said creatives could be a developer, a maker, an influencer, a marketer, a writer, etc.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "55",
        "name": "",
        "icon": "https://ph-files.imgix.net/cf942563-41e3-4591-a6eb-3c7f738a135b.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Gadget — The fastest way to build and run web apps",
        "description": "Gadget is a full-stack, serverless JavaScript platform for web app developers who want to build faster and maintain less. Skip the boilerplate features, repetitive code, and busywork, and get your ideas out the door in hours.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "56",
        "name": "",
        "icon": "https://ph-files.imgix.net/da70c17b-fabe-485d-bed8-413c8dcb0e0a.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Eden AI — Seamlessly Merging the Top AI APIs into One",
        "description": "Integrate Eden AI in your product to: 💪 Increase Accuracy & Reduce Cost by choosing the right AI API for each AI task ☮️ Gain peace of mind with centralized usage restrictions & cost monitoring 🌐 Continually explore emerging AI capabilities in the market",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "57",
        "name": "",
        "icon": "https://ph-files.imgix.net/7cf62972-6a64-45a7-b5f8-3e993d3f33ff.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Streamsync — Create UIs using a visual editor, code the backend in Python",
        "description": "Streamsync is an open-source framework for creating web-based data apps. Build user interfaces using a visual editor; write the backend code in Python. It's an alternative to Streamlit and Dash.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "58",
        "name": "",
        "icon": "https://ph-files.imgix.net/62006ec3-09e4-4880-b908-4fb54e9a498b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Supademo — Beautiful interactive demos and guides, in seconds",
        "description": "Supademo helps teams create interactive demos and guides in seconds. Close more deals, simplify onboarding, and accelerate time-to-value for your users. For free with no code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "59",
        "name": "",
        "icon": "https://ph-files.imgix.net/4de67e5e-dfad-44a0-979b-a8b66e6bf6a6.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "pxCode — A free UI Visual Programming Tool for React JS",
        "description": "Could you imagine turning your Deisgn into Responsive Webpage within 10 minutes? But with no Handoff, pxCode can help you acheive it!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "60",
        "name": "",
        "icon": "https://ph-files.imgix.net/3b26acd2-c3f4-4352-b1d5-24ffc2f465ef.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Creatomate — Create & automate videos by API and no-code",
        "description": "Creatomate is a video generation API for developers and Zapier users. Create reusable templates to automate and scale your video production with code or no-code tools. Auto-generate videos for social media, personalization, e-commerce, advertising, and more.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "61",
        "name": "",
        "icon": "https://ph-files.imgix.net/e4a610fc-074d-44e0-a650-3e3f12a672c6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Planet Crust — Connect to any data source, build whatever you want",
        "description": "Corteza by Planet Crust is a 100% open-source, 100% API-centric low-code platform that connects to any data source, then transforms your data into an open format so you quickly build and deploy web apps with easy-to-use workflows and drag-and-drop tools.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "62",
        "name": "",
        "icon": "https://ph-files.imgix.net/49bf83f7-c10b-4d6e-b314-51140d7ed78a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Puter — A computer in your browser",
        "description": "A fun, approachable, playful environment where you can build and share apps",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "63",
        "name": "",
        "icon": "https://ph-files.imgix.net/62134daa-5a82-4e4a-b63c-6fd5f8368f05.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Brizy — Next-gen website builder that anyone can use",
        "description": "Create 'no-code' websites in minutes. Once you go Brizy, nothing else feels easy!",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }