{
    "url": "https://www.producthunt.com/categories/security-compliance",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/dcd7544f-1c99-42be-be2b-e0cc80c463b0.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Ruby on Rails — A full-stack framework to build amazing web apps",
        "description": "Rendering HTML templates, updating databases, sending and receiving emails, maintaining live pages via WebSockets, enqueuing jobs for asynchronous work, storing uploads in the cloud, providing solid security protections for common attacks. Rails does it all and so much more.""productUrl":"",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/ec7c42b6-ea2f-479b-96d1-c34cfa9b10b1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloudflare — The web performance & security company",
        "description": "Cloudflare is a leading edge network services provider that offers a wide range of solutions to enhance the security, performance, and reliability of websites and applications. With its global network infrastructure and advanced technologies, Cloudflare empowers businesses to build a faster, more secure, and resilient online presence.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/297bc3d4-bd2e-4eaa-8fb6-a289cf61ea91.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Clerk — An authentication and user management platform",
        "description": "A complete suite of embeddable UIs, flexible APIs, and admin dashboards to authenticate and manage your users.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/ffb82f9d-697d-4b9f-8c05-5a5c34b39af5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Telegram 4.7 — Cloud-based, secure messaging app",
        "description": "Telegram Messenger is a globally accessible freemium, cross-platform, encrypted, cloud-based and centralized instant messaging service.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/2ac7c08f-c516-447a-9439-759ffb4fe184.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Infisical — Helping dev teams sync environment variables",
        "description": "A simple, end-to-end encrypted platform that enables Node.js teams to sync and manage their environment variables. Developers can modify start/dev scripts to pull and inject environment variables into local environments with 1 line of code.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/362dde8b-376b-41ba-b569-cb7970627b26.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Persona — Identity verification for any use case, starting at $0",
        "description": "Persona offers a suite of fully-automated identity verification components with worldwide coverage that can be configured and branded to create custom-tailored flows for any use case. Sign up for the Starter plan and start for free in <10 minutes.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/afa0d0ae-7cbb-46ec-869b-892d991b120a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "WorkOS — Your app, Enterprise Ready",
        "description": "WorkOS provides APIs to make your app Enterprise Ready, with pre-built features and integrations required by IT admins. Start selling to enterprise customers with just a few lines of code. Add Single Sign-On (SSO), Directory Sync, Audit Logs and more to your app today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/437602fd-635f-4367-b497-ce5ebdcd7471.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Stytch — User infrastructure for modern applications",
        "description": "Stytch is a full stack authentication and authorization platform, whose APIs make it simple to seamlessly onboard, authenticate and engage users. Improve security and user experience by going passwordless.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "9",
        "name": "",
        "icon": "https://ph-files.imgix.net/520f10cf-db80-4319-9ecc-c693e1558c87.svg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Sardine — A fraud and financial crime protection platform",
        "description": "Protect every customer interaction from financial crime. Used by banks, retailers, and fintechs to detect fraud patterns, prevent money laundering, and stop sophisticated scams.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/6819516b-a862-4aa0-908e-72f4a9a1ffa5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Middesk — A business identity platform",
        "description": "A suite of identity products to help companies across the US verify their commercial customers.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/245e6401-8144-4663-b12a-a11446a39958.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Auth0 — Secure access for everyone. But not just anyone.",
        "description": "Whether you’re a developer looking to innovate or a security professional looking to mitigate, we make identity work for everyone. Auth0 is the solution you need for web, mobile, IoT, and internal applications. Loved by developers and trusted by enterprises.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/dcc49a48-bd4e-422f-a98d-0a8092c1fb64.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Kinde — Simple, powerful authentication you can integrate in minutes",
        "description": "Everything you need for authentication wrapped in one beautiful platform. Free your users from passwords with secure and frictionless one click sign up and sign in. Out of the box support for Enterprise SSO like Azure AD. Let users sign in the way they want with built-in support for a range of social logins. Protect your users from reused or breached passwords with MFA. Stay on brand by customizing your sign up and sign in pages to match your look and feel. Built from the ground up using the best in class security protocols available today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/6eab1c05-92f8-416b-a19c-a42fc9ec53e8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Android 14 — Express yourself, take control, and stay safe",
        "description": "Android 14 is available today on Pixel phones 4A, 5G, and up with phones from Samsung, Nothing, and OnePlus. More supporting will be supporting it later this year.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/35b73e49-865c-4f43-833e-1c261db678be.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Gitsecure — AI-powered application security tool for engineering teams",
        "description": "",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "15",
        "name": "",
        "icon": "https://ph-files.imgix.net/5568900d-a099-4d0a-a268-dd7192f29037.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Doppler — Easily manage your environment variables and secrets",
        "description": "Doppler is the multi-cloud SecretOps Platform developers and security teams trust to provide secrets management at enterprise scale. Seamlessly manage and secure application secrets across cloud, environments, and team members.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "16",
        "name": "",
        "icon": "https://ph-files.imgix.net/817b39a7-1e9d-4994-9351-15d9d8ceb9df.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "1Password — The world’s most-loved password manager",
        "description": "1Password is a password manager, digital vault, form filler and secure digital wallet. Easily store and use strong passwords. Log in to sites and fill forms securely with a single click.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "17",
        "name": "",
        "icon": "https://ph-files.imgix.net/8a47f03c-5ebb-43bf-8340-d2eabb307b85.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Turnkey — Simple APIs to securely manage your crypto private keys",
        "description": "Introducing Turnkey, a new model for secure and easy-to-use private key infrastructure based on secure enclaves and built by the team behind Coinbase Custody. Create wallets, sign transactions, and easily manage access permissions for your team or end users.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "18",
        "name": "",
        "icon": "https://ph-files.imgix.net/948ff980-54cd-4e1c-b9fd-f79a8d7e8638.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Vanta — Automate compliance and streamline security reviews",
        "description": "Whether you’re starting or scaling your security program, Vanta helps you automate compliance across frameworks like SOC 2, ISO 27001, ISO 42001, HIPAA, HITRUST CSF, GDPR, and more. Streamline security reviews by automating questionnaires and demonstrating your security posture with a customer-facing Trust Center, all powered by Vanta AI. Over 7,000 global companies like Atlassian, Flo Health, and Quora use Vanta to manage risk and prove security in real time.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "19",
        "name": "",
        "icon": "https://ph-files.imgix.net/99b25702-dd13-48d7-8ebd-33051d0c40d3.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Datadog, Inc. — Monitoring and security platform for cloud applications",
        "description": "Datadog is a monitoring service for cloud-scale applications, providing monitoring of servers, databases, tools, and services, through a SaaS-based data analytics platform.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      },
      {
        "rank": "20",
        "name": "",
        "icon": "https://ph-files.imgix.net/a3a5a8d6-2705-4bdf-83a7-e72886f71c3c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Glasskube — 🧊 The next generation Package Manager for Kubernetes 📦",
        "description": "Building on the pitfalls of other popular package managers in the ecosystem, we aim to deliver streamlined package updates, easy GitOps integration, package dependency management, and simplified configuration options.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl": ""
      }
    ]
  }