{
    "url": "https://www.producthunt.com/categories/authentication-identity",
    "productCards": [
      {
        "rank": "1",
        "name": "",
        "icon": "https://ph-files.imgix.net/b9c546be-a73d-49be-84ac-92a774a5edfc.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Supabase — The open source Firebase alternative",
        "description": "Supabase is an open-source backend-as-a-service that provides real-time databases, authentication, and API services. It enables developers to build and scale applications quickly without managing server infrastructure.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "2",
        "name": "",
        "icon": "https://ph-files.imgix.net/cd6a3077-007d-4d68-a516-c8414b11bec8.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Firebase — An app development platform backed by Google",
        "description": "An app development platform that helps you build and grow apps and games users love. Backed by Google and trusted by millions of businesses around the world.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "3",
        "name": "",
        "icon": "https://ph-files.imgix.net/297bc3d4-bd2e-4eaa-8fb6-a289cf61ea91.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Clerk — An authentication and user management platform",
        "description": "A complete suite of embeddable UIs, flexible APIs, and admin dashboards to authenticate and manage your users.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "4",
        "name": "",
        "icon": "https://ph-files.imgix.net/ea1c7b5e-0f17-46b4-aff7-64a9bbf538f1.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Appwrite — 100% open source alternative for Firebase",
        "description": "A secure open-source backend server provides the core APIs required to build web and mobile applications. Appwrite provides authentication, database, storage, functions, messaging, and advanced realtime capabilities.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "5",
        "name": "",
        "icon": "https://ph-files.imgix.net/46057414-1dfa-4a70-b52c-12281b385f00.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Plaid — The safer way for your users to link financial accounts",
        "description": "The tools developers need to create easy and accessible experiences for their users. With just a few lines of code, users can connect to more than 12,000 financial institutions.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "6",
        "name": "",
        "icon": "https://ph-files.imgix.net/fcde694f-6982-4d00-864c-a3c180203ab6.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Memberstack — Authentication & Payments for Webflow. Total design freedom.",
        "description": "Memberstack empowers you to build anything - from gated blogs, to social media platforms - all using Memberstack & Webflow (or, whatever else you use to build sites & apps). Over 3,000 companies like Slack, Reddit, and American Airlines use Memberstack to build scalable, custom membership experiences. You can build everything you need without coding - but, you can also incorporate your own code into your projects and scale with Memberstack to a full-blown react application.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "7",
        "name": "",
        "icon": "https://ph-files.imgix.net/362dde8b-376b-41ba-b569-cb7970627b26.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Persona — Identity verification for any use case, starting at $0",
        "description": "Persona offers a suite of fully-automated identity verification components with worldwide coverage that can be configured and branded to create custom-tailored flows for any use case. Sign up for the Starter plan and start for free in <10 minutes.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "8",
        "name": "",
        "icon": "https://ph-files.imgix.net/afa0d0ae-7cbb-46ec-869b-892d991b120a.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "WorkOS — Your app, Enterprise Ready",
        "description": "WorkOS provides APIs to make your app Enterprise Ready, with pre-built features and integrations required by IT admins. Start selling to enterprise customers with just a few lines of code. Add Single Sign-On (SSO), Directory Sync, Audit Logs and more to your app today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "9",
        "name": "",
        "icon": "https://ph-files.imgix.net/437602fd-635f-4367-b497-ce5ebdcd7471.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Stytch — User infrastructure for modern applications",
        "description": "Stytch is a full stack authentication and authorization platform, whose APIs make it simple to seamlessly onboard, authenticate and engage users. Improve security and user experience by going passwordless.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "10",
        "name": "",
        "icon": "https://ph-files.imgix.net/36dac3fa-ed71-4def-992b-7178e2b78b26.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "ApparenceKit — Ship your mobile app in days, not months",
        "description": "ApparenceKit is a complete flutter boilerplate to help you ship a successful app on Android and iOS. Subscription, Notififications, Auth, Ads, translations, Architecture, Deployment....",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "11",
        "name": "",
        "icon": "https://ph-files.imgix.net/6819516b-a862-4aa0-908e-72f4a9a1ffa5.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Middesk — A business identity platform",
        "description": "A suite of identity products to help companies across the US verify their commercial customers.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "12",
        "name": "",
        "icon": "https://ph-files.imgix.net/245e6401-8144-4663-b12a-a11446a39958.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Auth0 — Secure access for everyone. But not just anyone.",
        "description": "Whether you’re a developer looking to innovate or a security professional looking to mitigate, we make identity work for everyone. Auth0 is the solution you need for web, mobile, IoT, and internal applications. Loved by developers and trusted by enterprises.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "13",
        "name": "",
        "icon": "https://ph-files.imgix.net/6c3c16e5-aa47-48d4-bfa4-60194620d51c.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Frontegg — Elegant user management, tailor-made for B2B SaaS",
        "description": "Everything your end-users need to manage their workspace in one integration, including authorization and authentication features and a customer-facing layer that allows them to gain full control over their accounts usage.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "14",
        "name": "",
        "icon": "https://ph-files.imgix.net/dcc49a48-bd4e-422f-a98d-0a8092c1fb64.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=14&h=14&fit=crop",
        "title": "Kinde — Simple, powerful authentication you can integrate in minutes",
        "description": "Everything you need for authentication wrapped in one beautiful platform. Free your users from passwords with secure and frictionless one click sign up and sign in. Out of the box support for Enterprise SSO like Azure AD. Let users sign in the way they want with built-in support for a range of social logins. Protect your users from reused or breached passwords with MFA. Stay on brand by customizing your sign up and sign in pages to match your look and feel. Built from the ground up using the best in class security protocols available today.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "15",
        "name": "",
        "icon": "https://ph-files.imgix.net/e1deaf8f-8d1c-45f1-991f-6f4952ae5ba9.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "staarter.dev — Launch Your Next SaaS Faster with staarter.dev",
        "description": "A comprehensive Next.js boilerplate that empowers developers to launch their SaaS applications quickly and efficiently. With features like authentication, subscription management, and localization, it provides a solid foundation so you can focus on innovating.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "16",
        "name": "",
        "icon": "https://ph-files.imgix.net/5568900d-a099-4d0a-a268-dd7192f29037.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Doppler — Easily manage your environment variables and secrets",
        "description": "Doppler is the multi-cloud SecretOps Platform developers and security teams trust to provide secrets management at enterprise scale. Seamlessly manage and secure application secrets across cloud, environments, and team members.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "17",
        "name": "",
        "icon": "https://ph-files.imgix.net/817b39a7-1e9d-4994-9351-15d9d8ceb9df.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "1Password — The world’s most-loved password manager",
        "description": "1Password is a password manager, digital vault, form filler and secure digital wallet. Easily store and use strong passwords. Log in to sites and fill forms securely with a single click.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "18",
        "name": "",
        "icon": "https://ph-files.imgix.net/b9c907c3-5a24-487f-8a76-a988c249e25b.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "PropelAuth — Authentication that works before you write any code",
        "description": "PropelAuth hosts and manages your authentication. Features like social logins, magic links, or managing profile pictures can be added in a single click. With our B2B support, your users can create organizations and invite their team members out of the box.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "19",
        "name": "",
        "icon": "https://ph-files.imgix.net/8a47f03c-5ebb-43bf-8340-d2eabb307b85.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Turnkey — Simple APIs to securely manage your crypto private keys",
        "description": "Introducing Turnkey, a new model for secure and easy-to-use private key infrastructure based on secure enclaves and built by the team behind Coinbase Custody. Create wallets, sign transactions, and easily manage access permissions for your team or end users.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "20",
        "name": "",
        "icon": "https://ph-files.imgix.net/0f4f1f87-ba3b-458c-81df-35582213f903.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Helm for App Store Connect — Easy Application Management",
        "description": "Meet Helm, an app designed to make it easier and more enjoyable for users of App Store Connect to ship apps and updates. Focused on providing a fast & intuitive user experience.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "21",
        "name": "",
        "icon": "https://ph-files.imgix.net/9bfc3f9b-3be8-43fb-8575-a4f437ef59ee.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Cloaked — Virtual identities to protect your privacy",
        "description": "Cloaked is a people-first privacy app that generates virtual identities to protect your personal data. No one should have to choose between staying connected and personal privacy — with Cloaked, you can try new products, travel, shop, and even meet new people while staying in control of your data. Unique and unlimited phone numbers, passwords, and payments set us apart from other privacy tools and password managers. Go ahead and give them your (Cloaked) info — and say goodbye to spam forever.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "22",
        "name": "",
        "icon": "https://ph-files.imgix.net/742f1bed-887e-409a-a511-0e9840445d9e.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "Capsule — Cross-app embedded wallet infrastructure",
        "description": "On a mission to radically simplify interacting with blockchains.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      },
      {
        "rank": "23",
        "name": "",
        "icon": "https://ph-files.imgix.net/a4e7b091-a934-4408-a9da-55166dc27fad.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=42&h=42&fit=crop",
        "title": "DiceBear — An avatar library for designers and developers",
        "description": "Create avatars for your profiles, designs, websites or apps. Piece by piece or based on a seed.",
        "productUrl":"",
        "websiteUrl":"",
        "imageUrl1":"",
        "imageUrl2":"",
        "imageUrl3":"",
        "videoUrl":""
      }
    ]
  }